### ISSUE TITLE
Add .gitignore for datasets/wakehealth

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#101]
We already pushed .DS_Store data on the repo.

**Comment by alexfoias** [comment]
@kousu I have pushed the fixes here: `datasets/wakehealth` on the branch`af/add_gitignore`.

Do you mind taking a look ? thanks

**Comment by alexfoias** [comment]
@kousu Could you please check the files ? thanks

**Comment by kousu** [comment]
Sorry sorry, just found this in my backlog.

It looks good and it's merged.
