### ISSUE TITLE
BIDSification `data_axondeepseg_tem`

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#102]
More info here: https://docs.google.com/presentation/d/1wI84Wt7tgTvbyopsHu0HwOAtgbk6eb8R5PJ7lB3awP8/edit#slide=id.ge2f19a181e_0_63

**Comment by alexfoias** [comment]
@mariehbourget Do we have to add it to internal git server ? If so, what name should we give it ?

**Comment by mariehbourget** [comment]
Yes, on git-annex for now. The name is `data_axondeepseg_tem`. Thanks!
