### ISSUE TITLE
Create dataset `sci-zurich`

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#109]
Linked to https://github.com/sct-pipeline/sci-lesion-segmentation/issues/1

**Comment by alexfoias** [comment]
I have added the data on `dataset/sci-zurich`

Log here: http://showterm.io/1218c52ad894217e9aa8c

@kousu or @jcohenadad Could you please review it ? thanks

**Comment by jcohenadad** [comment]
i assume you directly pushed to the main branch? i'm looking at it now

**Comment by alexfoias** [comment]
yes, the main branch because the repo is new. thanks

**Comment by jcohenadad** [comment]
data looks good! thank you @alexfoias 💯

**Comment by jcohenadad** [comment]
@alexfoias in the future, please add more context in the README. I'll take care of it for this one
