### ISSUE TITLE
Import dataset from Dropbox

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#115]
@jcohenadad requests:

>  a collaborator at U. Massachusetts shared 25GB of MRI data via Dropbox-- I can view them (because I have an upgraded account) but I don't have the time to put them in our internal git-annex server. They are already in BIDS format. Does any of you have a Dropbox account that can accommodate such size, allowing you to copy these data under the git-annex server?

**Comment by kousu** [comment]
I think the most direct way to do this is to use `rclone`: https://rclone.org/dropbox/. We can install that on one of our servers -- even directly on `data.neuro.polymtl.ca`, it's got 34G free on its /home right now so there's enough space to work with this dataset directly -- then download it with rclone and annex it.

rclone supports OAuth, and that page explains how to use it from the CLI: @jcohenadad just needs to click a link to grant access; he doesn't need to give us his password and the collaborator doesn't need to grant any additional permissions. Maybe Dropbox even supports requesting only a single subfolder?

**Comment by jcohenadad** [comment]
Amazing! Could we do it together next time we speak?

**Comment by jcohenadad** [comment]
We should create one BIDS dataset for each of the 4 shared datasets. 
The naming should be:
- `umass-ms-ge-excite1.5`
- `umass-ms-ge-hdxt1.5`
- `umass-ms-ge-pioneer3`
- `umass-ms-siemens-espree1.5`

**Comment by kousu** [comment]
Done

```
git@data:~/repositories/datasets$ du -x -d 0 -h umass-ms-*/annex | sort -h
456M	umass-ms-siemens-espree1.5.git/annex
762M	umass-ms-ge-excite1.5.git/annex
1.1G	umass-ms-ge-hdxt1.5.git/annex
26G	umass-ms-ge-pioneer3.git/annex
```

The `dataset_description.json` and `CHANGES` files are wrong but this is probably good enough for now.

**Comment by kousu** [comment]
To the future: sorry for not writing down what Julien and I did together. We basically just followed https://rclone.org/dropbox/ and then ran `rclone copy --progress ....`
