### ISSUE TITLE
"release" `uk-biobank-processed`

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#126]
From @sandrinebedard https://github.com/neuropoly/data-management/issues/114#issue-988607164

> I also wanted to add a release tag to the dataset after we merge this PR, not sure how to do that with git annex!

**Comment by kousu** [comment]
This is relatively straightforward, we just need to agree on what to call the tag first. Once we do that I can walk you through doing this @sandrinebedard :)

**Comment by sandrinebedard** [comment]
Great! So this is the fisrt release of the dataset, mainly, we now have all the segmentations, vertebral labelings and PMJ labels for T1w data used for my project https://github.com/sct-pipeline/ukbiobank-spinalcord-csa

**Comment by kousu** [comment]
We opened up https://git-scm.com/book/en/v2/Git-Basics-Tagging as a reference.

We looked through

* https://github.com/spinalcordtoolbox/spinalcordtoolbox/releases
* https://github.com/spine-generic/data-single-subject/releases - r+`date`
* https://github.com/spine-generic/data-multi-subject/releases - r+`date`
* https://github.com/ivadomed/ivadomed/releases/ - "v"+semver
* https://github.com/axondeepseg/model_seg_rat_axon-myelin_sem/releases - r+`date`
* https://github.com/axondeepseg/default-SEM-model/releases/ - r+`date`
* https://github.com/axondeepseg/data-example/releases - r+`date`
* https://github.com/axondeepseg/data_axondeepseg_sem/releases - r+`date`
* https://github.com/ivadomed/data-testing/releases - r+`date`
* https://github.com/ivadomed/data_functional_testing/releases - r+`date`

as well as

* https://github.com/OpenNeuroDatasets/ds000247/releases - semver
* https://github.com/OpenNeuroDatasets/ds000116/releases - semver
* https://github.com/OpenNeuroDatasets/ds001499/releases - semver

and decided that on balance, in the lab, we're using the "rYYYYMMDD" format for tagging datasets.

So @sandrinebedard typed:

```
git tag -a r20210928
```

Then filled in a message with some release notes, then did

```
git show r20210928
```

to verify `r20210928` was currently pointed at `master` and had saved the release notes

```
$ git show r20210928
tag r20210928
Tagger: Sandrine Bédard <sebeda@abbey.neuro.polymtl.ca>
Date:   Tue Sep 28 13:42:45 2021 -0400

First release. The derivatives include all manually verified and corrected spinal cord segmentations, vertebral labeling and PMJ labels for T1w images.

commit 7ed28cd0aacaab0ce1570bccdba3bff495b5f496 (HEAD -> master, tag: show, tag: r20210928)
Author: Sandrine Bedard <sandrine.bedard@polymtl.ca>
Date:   Sun Sep 5 17:49:04 2021 -0400

    change suffix in derivatives from labels-manual to labels-disc-manual

```

and finally uploaded:

```
git push origin r20210928
```

I ssh'd in with my admin powers and verified that the tag made it to the server:

```
git@data:~/repositories/datasets/uk-biobank-processed.git$ git show r20210928
tag r20210928
Tagger: Sandrine Bédard <sebeda@abbey.neuro.polymtl.ca>
[...]
```

`gitolite` doesn't have a nice "releases" pane the way Github does -- it would be somewhat redundant.
