### ISSUE TITLE
`gitolite releases`

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#129]
Github has these nice release summaries: https://github.com/spinalcordtoolbox/optic_models/releases

Can we create the same for `gitolite`? It would be somewhat redundant since the interface to "releases" (i.e. git tags) is already straightforward on the command line. It would be the difference between

```
git clone git@data.neuro.polymtl.ca:datasets/uk-biobank-processed && cd uk-biobank-processed && git tag -l
```

and

```
ssh git@data.neuro.polymtl.ca releases datasets/uk-biobank-processed
```

but the advantage of the latter is you could look through releases without having to download anything first; and then you could download only the minimally necessary part (with `clone -b`):

```
git clone --depth 1 -b r20210923 git@data.neuro.polymtl.ca:datasets/uk-biobank-processed
```

**Comment by jcohenadad** [comment]
Maybe consider contacting the gitoline folks with that question (ie: do they already have that feature or planning to develop it?)

**Comment by kousu** [comment]
reminder: gitolite contact point is gitolite@googlegroups.com
