### ISSUE TITLE
`spine-generic-processed`: `-MT{on,off}` -> `_mt-{on,off}`

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#147]
According to https://bids-specification.readthedocs.io/en/latest/99-appendices/10-file-collections.html#magnetic-resonance-imaging, the naming format is 

```
            sub-<label>[_ses-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_echo-<index>]_flip-<index>_mt-<on|off>[_part-<mag|phase|real|imag>]_MTS.json
            sub-<label>[_ses-<label>][_acq-<label>][_ce-<label>][_rec-<label>][_run-<index>][_echo-<index>]_flip-<index>_mt-<on|off>[_part-<mag|phase|real|imag>]_MTS.nii[.gz]
```

Notice how it says to use `_mt-<on|off>`.

Meanwhile we have

```
u108545@joplin:~/spine-generic-processed$ tree
[...]
└── sub-vuiisIngenia06
    ├── anat
    │   ├── sub-vuiisIngenia06_acq-MToff_MTS.json
    │   ├── sub-vuiisIngenia06_acq-MToff_MTS.nii.gz
    │   ├── sub-vuiisIngenia06_acq-MTon_MTS.json
    │   ├── sub-vuiisIngenia06_acq-MTon_MTS.nii.gz
    │   ├── sub-vuiisIngenia06_acq-T1w_MTS.json
    │   ├── sub-vuiisIngenia06_acq-T1w_MTS.nii.gz
    │   ├── sub-vuiisIngenia06_T1w.json
    │   ├── sub-vuiisIngenia06_T1w.nii.gz
    │   ├── sub-vuiisIngenia06_T2star.json
    │   ├── sub-vuiisIngenia06_T2star.nii.gz
    │   ├── sub-vuiisIngenia06_T2w.json
    │   └── sub-vuiisIngenia06_T2w.nii.gz
    └── dwi
        ├── sub-vuiisIngenia06_dwi.bval
        ├── sub-vuiisIngenia06_dwi.bvec
        ├── sub-vuiisIngenia06_dwi.json
        ├── sub-vuiisIngenia06_dwi.nii.gz
        └── sub-vuiisIngenia06_rec-average_dwi.nii.gz
```

i.e. `-MT<on|off>`. So we're not compliant here.

**Comment by kousu** [comment]
I bet our other datasets have the same problem!

**Comment by jcohenadad** [comment]
> I bet our other datasets have the same problem!

yup! they definitely do

**Comment by kousu** [comment]
In fact it's not just that we're using the `-MT` field and forgot the separator like I read this. Instead we're embedding the `mt-` field inside the `acq-` field, which is supposed to be for something else entirely.

**Comment by jcohenadad** [comment]
just for the context/justification: the reason we are not compliant is because the BIDS extension proposal for qMRI (which includes the MT contrast) came up _after_ we put together this database. But now, we know what to do

**Comment by kousu** [comment]
Fixed in https://github.com/spine-generic/data-multi-subject/pull/105 with 

```bash


find . -name "*_acq-MT*.nii.gz" |
 while read fname; do
   git mv ${fname} ${fname/_acq-MT/_mt-};
 done
```

so, that should be easy to port here.

**Comment by kousu** [comment]
> just for the context/justification: the reason we are not compliant is because the BIDS extension proposal for qMRI (which includes the MT contrast) came up _after_ we put together this database. But now, we know what to do

I'm sorry if I'm coming off cold? I'm being terse because I'm seeing a lot of things to nitpick and I want to get them all written down before I forget.

**Comment by valosekj** [comment]
Solved within https://github.com/spine-generic/data-multi-subject/pull/135 --> closing this issue.
