### ISSUE TITLE
Upload `data_axondeepseg_bf_source` and `data_axondeepseg_bf_training` to git-annex

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/data-management#152]
I don't know if this is the right place to ask for this. Please let me know if it's not.

We have 2 optical microscopy ADS datasets ready to be upload to the git-annex server.
They are already in BIDS-format and can be upload "as is".
They are `data_axondeepseg_bf_source` and `data_axondeepseg_bf_training` available in `duke/projects/axondeepseg/20211105_bf_datasets`.

Thank you!

**Comment by kousu** [comment]
Yep, that's easy. The docs for it are at https://github.com/neuropoly/data-management/blob/master/internal-server.md#new-repository.

I can take care of it for you though, it'll be quick.

**Comment by mariehbourget** [comment]
Hi @kousu, thank you for the info!
As our BIDS specification for microscopy is moving along quite fast at the moment, it seems that I'll have changes to do in the dataset in the very short term. So I'll wait a little bit before uploading to git-annex.
I'll let you know if I need help, thanks!

**Comment by hermancollin** [comment]
Both datasets are now on the internal data server.

**Comment by mariehbourget** [comment]
> Both datasets are now on the internal data server.

Thank you @hermancollin! 🙏
