### ISSUE TITLE
fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#155]
I'm trying to update a git-annex dataset, but i am getting this:

~~~julien-macbook:~/data.neuro/spine-generic-processed $ git pull && git annex sync --no-content && git annex get .
git@data.neuro.polymtl.ca: Permission denied (publickey,password).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
~~~

**Comment by jcohenadad** [comment]
in fact, i cannot connect to any station anymore 🤔

**Comment by kousu** [comment]
We fixed this over in https://github.com/neuropoly/data-management/issues/154#issuecomment-983836310...also this isn't really a data-management issue, it's a tech support issue.

**Comment by jcohenadad** [comment]
> also this isn't really a data-management issue, it's a tech support issue.

which repository should tech support issue be opened in the future?

**Comment by kousu** [comment]
I guess we don't have a good option. After investigation, https://github.com/neuropoly/intranet.neuro.polymtl.ca would be most appropriate since it was related to the SSH advice from that page over there. But it wouldn't be clear that that was the problem before investigation.
