### ISSUE TITLE
basel-mp2rage: branch af/add_data_katrin

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#157]
I'm just seeing this branch:

~~~
To data.neuro.polymtl.ca:datasets/basel-mp2rage
   a9d4b49..80adc00  git-annex -> synced/git-annex
 * [new branch]      af/add_data_katrin -> synced/af/add_data_katrin
~~~

is this branch merged? is there anything needed to review?

Also: is there an issue/discussion that describes the purpose of this branch?

**Comment by alexfoias** [comment]
This comes from https://github.com/neuropoly/data-management/pull/125

**Comment by jcohenadad** [comment]
duplicate from #125

**Comment by jcohenadad** [comment]
@alexfoias i suggest adding the name of the dataset in the issue title-- i've just edited-- easier to search-- thx
