### ISSUE TITLE
Unable to Update Dataset with `git-annex`

### ISSUE THREAD

**Issue by uzaymacar** [neuropoly/data-management#158]
The following commands

```
git clone git@data.neuro.polymtl.ca:datasets/basel-mp2rage
cd basel-mp2rage
git pull && git annex sync --no-content && git annex get .
```

give the following error

```
Already up to date.
(scanning for unlocked files...)
commit 
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
ok
pull origin 

Merge made by the 'recursive' strategy.
 .DS_Store                    | Bin 0 -> 12292 bytes
 derivatives/.DS_Store        | Bin 0 -> 6148 bytes
 derivatives/labels/.DS_Store | Bin 0 -> 14340 bytes
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .DS_Store
 create mode 100644 derivatives/.DS_Store
 create mode 100644 derivatives/labels/.DS_Store
ok
push origin 
FATAL: W any datasets/basel-mp2rage uzmac DENIED by fallthru
(or you mis-spelled the reponame)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: W any datasets/basel-mp2rage uzmac DENIED by fallthru(or you mis-spelled the reponame)fatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.  Pushing to origin failed.
failed
git-annex: sync: 1 failed
```

while trying to update the `basel-mp2rage` dataset to its version with two annotators.

**Comment by jcohenadad** [comment]
It seems like you used a mix of commands between 'downloading' and 'updating' the repository. The 'update' syntax that you used:
~~~
git pull && git annex sync --no-content && git annex get .
~~~

should only be used _if_ you already have cloned the repository.

But if you want to clone from scratch, then you should do:
~~~
git clone git@data.neuro.polymtl.ca:datasets/basel-mp2rage
cd basel-mp2rage
git annex get .
~~~

So, could you try to _only_ clone a fresh repository? 

Also: it would be useful to see your entire Terminal output.

**Comment by uzaymacar** [comment]
I was cloning from scratch earlier, and that does work for me. However, I don't see the the second annotator (`_manual2`) in the dataset when I download it.

**Comment by jcohenadad** [comment]
> I was cloning from scratch earlier, and that does work for me (i.e. executes w/o error). However, I don't see the the second annotator (_manual2) in the dataset when I download it. (To be clear, I still don't see it when I clone it now)

Indeed, I just realized that they are still not merged. You can access it by switching to the correct branch. More details at: https://github.com/neuropoly/data-management/pull/125

**Comment by uzaymacar** [comment]
Ah I see, I now have access to the data, thanks! Closing the issue.

**Comment by kousu** [comment]
> ```
> FATAL: W any datasets/basel-mp2rage uzmac DENIED by fallthru(or you mis-spelled the reponame)fatal: Could not read from remote repository.Please make sure you have the correct access rightsand the repository exists.  Pushing to origin failed.
> ```


this is saying: Uzay doesn't have write permissions to this dataset. And that's fine. Our standing policy is to only grant write access on a case-by-case basis to derisk our workflow.

@uzaymacar if you do

```
git config remote.origin.annex-readonly true
```

then the errors will go away.

You can also do

```
git pull && git annex sync --no-content ; git annex get .
```

to get the data, or

```
git pull && git annex sync --no-push --no-content && git annex get .
```

or 

```
git config remote.origin.annex-sync false && git pull && git annex sync --no-push --no-content && git annex get .
```

or 


```
git config remote.origin.annex-push false && git pull && git annex sync --no-push --no-content && git annex get .
```


because `git-annex` has made the UI mistake of giving many non-orthogonal options.

or even side-step git-annex with

```
git checkout --quiet --detach HEAD && git fetch origin master:master git-annex:git-annex && git checkout --quiet - && git annex get .
```


I haven't put this advice in the docs because I don't know how to pick a canonical method nor square it with the fact that, for people who *do* have write access, they should *not*. Please help me pick.

**Comment by jcohenadad** [comment]
Currently the doc says:
~~~
git pull && git annex sync --no-content ; git annex get .
~~~

Which Uzay seems to be able to use (he managed to access the data at the end), so I assume we can leave it as it is? I agree we should try to minimize the amount of options we give to our users

**Comment by kousu** [comment]
Actually it says 

```
git pull && git annex sync --no-content && git annex get .
```

which is different: because `git annex` wasn't able to (needlessly) write back, it returned 1 so actually downloading the data was skipped.

And if we document the `;` version, people will end up with stray errors and be trained to ignore what git-annex says to them

**Comment by jcohenadad** [comment]
> Actually it says

indeed, i missed that subtlety. We can agree on what is the best way to document for lab members in https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/38
