### ISSUE TITLE
Move Beijing data to git-annex

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#162]
from: projects/ivadomed/tumor_segmentation_20201005
to: git-annex/datasets/beijing-tumor

**Comment by alexfoias** [comment]
@jcohenadad do you want me to take care of it ?

**Comment by jcohenadad** [comment]
that would be great! thank you @alexfoias 🙏

**Comment by alexfoias** [comment]
@jcohenadad Added the it to`datasets/beijing-tumor`

[log.txt](https://github.com/neuropoly/data-management/files/7715035/log.txt)

**Comment by jcohenadad** [comment]
thx-- todo:
- remove duplicates on duke

**Comment by alexfoias** [comment]
@jcohenadad is done.

Here is the proof:

```
> pwd
/Volumes/projects/ivadomed
> ll
total 48680
drwx------  1 alex  staff   264B 20 May  2021 LongitudinalMultipleSclerosisLesionSegmentationChallengeMiccai21
drwx------  1 alex  staff   1.4K 19 May  2021 LongitudinalMultipleSclerosisLesionSegmentationChallengeMiccai21_ANIMApreprocess
drwx------  1 alex  staff   264B  9 Mar  2021 MIDL_film_2021
drwx------  1 alex  staff   264B 29 Dec  2020 brats
drwx------  1 alex  staff   8.7K 26 Jul  2020 data-multi-subject
drwx------  1 alex  staff   8.8K 29 Dec  2020 data-multi-subject-registered
drwx------  1 alex  staff   2.8K  1 Mar  2021 gm_challenge_16
drwx------  1 alex  staff   1.5K 12 May  2021 gm_challenge_16_inter_rater
-rwx------  1 alex  staff    24M 31 Mar  2021 gm_t2_exvivo__20210331_223156.zip
drwx------  1 alex  staff   264B 31 Mar  2021 gm_t2_exvivo__wrong_orientation
drwx------  1 alex  staff   264B 19 Jan  2021 leander
drwx------  1 alex  staff   264B 11 Nov  2019 lucas_vertebral_labeling
drwx------  1 alex  staff   264B 15 Jun  2021 ms_brain_DoNotUse
drwx------  1 alex  staff   1.5K 27 May  2021 ms_challenge_2021_bids_DoNotUse
drwx------  1 alex  staff   1.5K  9 Jun  2021 ms_challenge_2021_preprocessed_sct_output
drwx------  1 alex  staff   264B  3 Jun  2021 ms_challenge_2021_preprocessing_QC
drwx------@ 1 alex  staff   364B 15 Nov  2019 ms_inter_rater
drwx------  1 alex  staff   264B 10 Mar  2021 ms_lesion_seg_karolinska
drwx------  1 alex  staff   432B 14 Oct  2020 olivier
drwx------  1 alex  staff   364B 21 Oct  2020 ometif_5d_datasets_examples
drwx------  1 alex  staff   840B 21 Jul 15:38 scripts_internal
drwx------  1 alex  staff   670B 21 Jul  2020 soft_L2_vs_Dice
drwx------  1 alex  staff   264B 28 Dec  2020 soft_vs_hard
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201903031331
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201904040901
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201904111053
drwx------  1 alex  staff   398B  4 Sep  2019 spineGeneric_201904271322
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201906281200
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201906301200
drwx------  1 alex  staff   264B  4 Sep  2019 spineGeneric_201907041011
drwx------  1 alex  staff   264B 28 Feb  2020 spineGeneric_202002200220
drwx------  1 alex  staff   2.9K 22 Nov  2020 spleen_kidney
drwx------  1 alex  staff   264B 28 Nov  2019 testing_data
drwx------  1 alex  staff   1.5K 27 May  2021 tmp_ms_challenge_2021
drwx------  1 alex  staff   1.5K 11 Jun  2021 tmp_ms_challenge_2021_preprocessed
drwx------  1 alex  staff    12K 20 Aug  2020 tumor_segmentation_20200820
drwx------  1 alex  staff    12K 23 Sep  2020 tumor_segmentation_20200923
drwx------  1 alex  staff   264B  7 Jul  2020 tutorial_datasets
```

**Comment by alexfoias** [comment]
We can close the issue.

**Comment by jcohenadad** [comment]
Before that I would like to better document in the duke folder, because there are still some "tumor_segmentation_*" folders out there.

@andreanne-lemay can we safely remove these folders:
- tumor_segmentation_20200820
- tumor_segmentation_20200923

**Comment by jcohenadad** [comment]
Also, we need to update the data provenance info here:
- https://github.com/ivadomed/findcord_tumor
- https://github.com/ivadomed/model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel/issues/4

**Comment by andreanne-lemay** [comment]
Data provenance and more info were added to the model's repo (https://github.com/ivadomed/findcord_tumor/pull/3, https://github.com/ivadomed/model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel/pull/5).

> Before that I would like to better document in the duke folder, because there are still some "tumor_segmentation_*" folders out there.
> 
> @andreanne-lemay can we safely remove these folders:
> 
> * tumor_segmentation_20200820
> * tumor_segmentation_20200923

I think it's fine to delete them, but before giving my approval to do so, I would like to verify the content of these folders. Currently, I can't access duke (I contacted the DGE), so I'll update this issue when I do the verification.

**Comment by alexfoias** [comment]
@andreanne-lemay could you please give us an update ? thank you.

**Comment by andreanne-lemay** [comment]
> @andreanne-lemay could you please give us an update ? thank you.

Sorry for the delay! After verification, these folders can be deleted. Thank you for taking care of this!

**Comment by alexfoias** [comment]
I removed the folders: 
```
~/duke/projects/ivadomed/tumor_segmentation_20200820
~/duke/projects/ivadomed/tumor_segmentation_20200923
```

**Comment by alexfoias** [comment]
I updated the info here:

- https://github.com/ivadomed/findcord_tumor
- Procedure and config file to reproduce the model ivadomed/model_seg_sctumor-edema-cavity_t2-t1_unet3d-multichannel#4

**Comment by alexfoias** [comment]
@jcohenadad @andreanne-lemay I think all the requested actions are done. I suggest closing the issue.
