### ISSUE TITLE
added manual SC segmentations for few subjects in the `sci-zurich` dataset

### ISSUE THREAD

**Issue by naga-karthik** [neuropoly/data-management#167]
Manual segmentations of the spinal cord (SC) of 3 subjects were added to the derivatives of the `sci-zurich` dataset. 

**Problem:** SCT was used for cropping the input data which resulted in the SC lesions also being cropped for 3 subjects `sub-zh11` (`ses-01` and `ses-02`), `sub-zh12` (`ses-01`), and `sub-zh17` (`ses-01`). 

**Solution:** SCT's incomplete output for these subjects was extended by adding manual segmentations such that the SC lesions are covered by the manual segmentation. This resulted in sufficient cropping of the input data without losing any lesion information for all the subjects (tested by running `sct_run_batch` again on the updated dataset on `joplin`). In addition, the README is also updated with this latest change.  

Figure below shows that only 4 files were added (and the README was modified)

![sci-zurich-manual](https://user-images.githubusercontent.com/53445351/150016399-1e5f48f3-edd2-4f34-9e53-2e6268b3852d.PNG)

@jcohenadad Would you please be able to review this PR? Thank you in advance! :)

**Comment by jcohenadad** [comment]
@naga-karthik happy to review-- what is your branch name pls?

**Comment by jcohenadad** [comment]
Reviewed and accepted!

<details><summary>Terminal output</summary>

```console
julien-macbook:~/data.neuro/sci-zurich $ git merge --ff-only nk/manual_seg
Updating 4ef05bf..d823215
Fast-forward
 README                                                                                | 3 +++
 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_seg-manual.nii.gz | 1 +
 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_seg-manual.nii.gz | 1 +
 derivatives/labels/sub-zh12/ses-01/anat/sub-zh12_ses-01_acq-sag_T2w_seg-manual.nii.gz | 1 +
 derivatives/labels/sub-zh17/ses-01/anat/sub-zh17_ses-01_acq-sag_T2w_seg-manual.nii.gz | 1 +
 5 files changed, 7 insertions(+)
 create mode 100644 derivatives/labels/sub-zh11/ses-01/anat/sub-zh11_ses-01_acq-sag_T2w_seg-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh11/ses-02/anat/sub-zh11_ses-02_acq-sag_T2w_seg-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh12/ses-01/anat/sub-zh12_ses-01_acq-sag_T2w_seg-manual.nii.gz
 create mode 100644 derivatives/labels/sub-zh17/ses-01/anat/sub-zh17_ses-01_acq-sag_T2w_seg-manual.nii.gz
julien-macbook:~/data.neuro/sci-zurich $ git push
Total 0 (delta 0), reused 0 (delta 0)
To data.neuro.polymtl.ca:datasets/sci-zurich
   4ef05bf..d823215  master -> master
```

</details>

@alexfoias Can you please make sure it has been properly pushed on master?

**Comment by alexfoias** [comment]
@jcohenadad @naga-karthik I have checked the repo and everything seems to have been pushed correctly. We can close the issue.

**Comment by naga-karthik** [comment]
Sounds good! Thank you for the confirmation @alexfoias! Closing it!
