### ISSUE TITLE
add more data to `sci-zurich`

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#170]
The data was sent in the email : `Re: Subsegmenting GM and WM` on `March 16, 2022 12:11 PM`.

I initially pushed all of them on `af/add_data`, but it also has .nii (which I didn't realize until the moment of pushing them).

I am currently working on fixing it issue. 

@naga-karthik @uzaymacar @kousu Tagging you to be aware of developments.

**Comment by alexfoias** [comment]
@naga-karthik Could you please review branch `af/add_extra_data` ?

@kousu How can I remove the branch `af/add_data`? thanks

**Comment by naga-karthik** [comment]
Hey @alexfoias! I have gone through your branch and there are some things that need to be updated. 

1. As mentioned in the email by Dario, there is no data for `sub-zh28`, however, their name still exists in the `participants.tsv` file. So, the `sub-zh28` row in this file must be deleted. 
2. As also mentioned, there are some subjects with no hyperintense lesions (i.e. no nifti file in the derivatives folder). I have identified those subjects (shown below), they also have to be removed from the dataset. 

```
Subject with NO Lesion(s):  [['sub-zh24', 'ses-01'], ['sub-zh50', 'ses-01'], ['sub-zh65', 'ses-01'], ['sub-zh67', 'ses-01'], ['sub-zh73', 'ses-01'], ['sub-zh74', 'ses-01']]
```

**NOTE**:  I have updated the branch with the changes listed above, the updated dataset now has **74 subjects** (see commit hash 39737375a7fe4d4dc7e0c74e57ab364f1e78bc4d).

**Comment by alexfoias** [comment]
@naga-karthik I pushed the data received on 2022-03-24 on `af/new_data_zurich`.

**Comment by alexfoias** [comment]
Added new data on `af/additional_data` https://gist.github.com/alexfoias/c9861f661132309f80c32b77d54d5eb3

**Comment by alexfoias** [comment]
@naga-karthik changed the data and now it's merged to master.
