### ISSUE TITLE
merge INsIDER_SCT_Segmentations_COR to basel-mp2rage git annex

### ISSUE THREAD

**Issue by kiristern** [neuropoly/data-management#181]

**Comment by mguaypaq** [comment]
This is now merged into master. To make `bids-validator` happy, I also added two extra commits to:
1. rename the `scripts/` folder to `code/`, and
2. delete the empty JSON sidecar files.

After these changes, the following steps work:
```
git clone git@data.neuro.polymtl.ca:datasets/basel-mp2rage
cd basel-mp2rage/
git annex dead here
git annex get
bids-validator .
```
