### ISSUE TITLE
`sct-testing-large` - rename CSM to DCM

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#183]
Based on a discussion with Julien, I unified the `pathology` column for patients with spinal cord compression in the `data.neuro.polymtl.ca/datasets/sct-testing-large/participants.tsv` file. Namely, I renamed `CSM` (Cervical Spondylotic Myelopathy) to `DCM` (Degenerative Cervical Myelopathy). My branch is named `jv/rename_CSM_to_DCM`.

**Comment by mguaypaq** [comment]
I'm not finding any other instances of `CSM` anywhere, so it looks like the rename is complete. Merged into `master`.
