### ISSUE TITLE
Conversion of `duke/mri/INSPIRED/` to BIDS

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#184]
During the BIDSification of the `duke/mri/INSPIRED/` dataset, I came across the following points, which I would like to discuss.

## 1. Two centers

Since the `INSPIRED` dataset is from two centers (Zurich and Toronto), I would choose the following participant_ids: 

* `sub-zurich`
* `sub-toronto`

## 2. Three pathologies
 
Within each centre, there are 3 types of subjects: `csm`, `hc`, `sci`. That's fine; this information will be passed on to the participants.tsv column `pathology`. The complication is that there is an overlap in the numbering of subjects within pathologies. In other words, for example, the subject `001` is included in both `csm` and `hc`:

<details><summary>tree</summary>

```
$ tree -L 2 
.
├── csm
│   ├── 001
│   ├── 005
│   ├── 006
│   ├── 007
│   ├── 008
│   ├── 009
│   ├── 010
│   ├── 015
│   ├── 017
│   ├── 018
│   ├── 019
│   ├── 021
│   ├── 022
│   └── 023
├── hc
│   ├── 001
│   ├── 002
│   ├── 004
│   ├── 005
│   ├── 006
│   ├── 007
│   ├── 009
│   ├── 010
│   ├── 011
│   ├── 012
│   ├── 013
│   ├── 014
│   ├── 015
│   └── 016
└── sci
    ├── 003
    └── 012
```

</details>

Thus, some re-numbering will have to be done. I would vote for something like this:

| participant_id | pathology | data_id | institution_id | institution |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| sub-zurich-001 | csm | 001 | zurich | Zurich |
| sub-zurich-002 | csm | 005 | zurich | Zurich |
| ... | ... | ... | ... | ... |
| sub-zurich-015 | hc | 001 | zurich | Zurich |
| ... | ... | ... | ... | ... |

This approach would store the original subject numbering within the `data_id` column.

## 3. Two regions

There are two anatomical regions: `brain` and `cord`:

<details><summary>tree</summary>

```
$ tree -L 5
.
├── csm
│   ├── 001
│   │   └── bl
│   │       ├── brain
│   │       │   ├── dwi_ad1000.nii.gz
│   │       │   ├── dwi.bval
│   │       │   ├── dwi.bvec
│   │       │   ├── dwi_md1000.nii.gz
│   │       │   ├── dwi.nii.gz
│   │       │   ├── dwi_rd1000.nii.gz
│   │       │   ├── dwi_reversed_blip.nii.gz
│   │       │   ├── mpm_A.nii.gz
│   │       │   ├── mpm_MT.nii.gz
│   │       │   ├── mpm_MT_std_Cerebellum.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_BiasCorrected.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_Brain.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_Parcellation.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_prior.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_Segmentation_clean.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_Segmentation_flat.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_Segmentation.nii.gz
│   │       │   ├── mpm_MT_std_NeuroMorph_TIV.nii.gz
│   │       │   ├── mpm_MT_std.nii.gz
│   │       │   ├── mpm_R1_UNICORT.nii.gz
│   │       │   ├── mpm_R2s_OLS.nii.gz
│   │       │   └── mpm_raw
│   │       └── cord
│   │           ├── dwi.bval
│   │           ├── dwi.bvec
│   │           ├── dwi.nii.gz
│   │           ├── dwi_reversed_blip.nii.gz
│   │           ├── pd_medic.nii.gz
│   │           ├── sct_processing
│   │           ├── t1_sag.nii.gz
│   │           ├── t2_sag.nii.gz
│   │           └── t2_tra.nii.gz
...
```

</details>

How to deal with it? Split the dataset into two separate datasets (e.g., `inspired_brain` and `inspired_cord`)? Or use the `ses` label? Something like:

```
├── sub-zurich-001
│   ├── ses-brain
│   │    ├── anat
│   │    └── dwi
│   ├── ses-cord
│   │    ├── anat
│   │    └── dwi
```

**Comment by jcohenadad** [comment]
- `sub-zurich-001` is not BIDS compliant, see definitions of [subject](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#filesystem-structure) and [<label>](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#definitions)(item 10). Suggestion: `sub-zurich001`
- About "The complication is that there is an overlap in the numbering of subjects within pathologies.", my suggestion is to do `sub-zurichDCM001`, `sub-zurichHC001`, etc. if we want to be able to recognize groups more easily.
- Please change csm for DCM to be consistent with NeuroPoly's lab standard 
- Please use capital letters in the participant.tsv file (HC, DCM, SCI) to be consistent with NeuroPoly's lab standard
- About "There are two anatomical regions: brain and cord:": do not use ses. You can specify spinal cord -- see cneuromod project (no time to add link now -- will do later-- or @mathieuboudreau can help)

**Comment by valosekj** [comment]
> * About "There are two anatomical regions: brain and cord:": do not use ses. You can specify spinal cord -- see cneuromod project (no time to add link now -- will do later-- or @mathieuboudreau can help)

Found:
https://github.com/courtois-neuromod/anat/tree/main/sub-01/ses-001/anat
https://github.com/courtois-neuromod/anat/issues/1#issuecomment-645364454

I'll use `bp-cspine`. Thank you 👍🏻

**Comment by jcohenadad** [comment]
> I'll use bp-cspine.

exactly! good

**Comment by jcohenadad** [comment]
@valosekj new info from UCL: inspired01 = Toronto; inspired02 = Zurich

**Comment by valosekj** [comment]
> @valosekj new info from UCL: inspired01 = Toronto; inspired02 = Zurich

Thank you!

**Comment by valosekj** [comment]
Data BIDSified and uploaded to git-annex, see https://github.com/neuropoly/data-management/issues/208 --> closing
