### ISSUE TITLE
Set up and document workflow for contributing to the private datasets

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#19]
This is a WIP -- suggestions welcome

- Set up two roles: CREATORS | WRITERS
- WRITERS:
  - can create new branches (e.g. to submit manual segmentations, add datasets)
  - cannot write to master

Typical workflows:
- Upload manual segmentations
  - User in the WRITERS group would make the modification locally
  - Would create a new branch and commit/push to that branch
  - Someone in CREATORS review the proposition and eventually accepts

Backup strategies:
- In case a PR is wrongly merged, we would need to [mirror](https://gitolite.com/gitolite/mirroring.html) the sensitive repository somewhere else. E.g. UNF.

**Comment by kousu** [comment]
I went to the DataLad meetup (at 9am EST every Tuesday) in https://meet.jit.si/DataLad this morning and asked about Pull Requests. The answer I got was: there is no good answer. I got some suggestions in lieu:

To fit into the ideal everyone-has-their-own-fork model that git encourages:

- take pull requests via GitHub; submitters set up [a git-lfs special-remote](https://git-annex.branchable.com/tips/storing_data_in_git-lfs/)
    - but submitters need to periodically **delete** their fork, because otherwise Github will charge them a [huge amount of money for the bill](https://github.community/t/what-are-the-pricing-plans-for-git-lfs-is-there-something-better-than-git-lfs-to-use/519)

With our internal server

- just have everyone sync to the same server (what I was planning to do)
    - periodically run `git annex find --unused | while read file; do git annex drop $file; done` to clean up un-merged files
    - but this needs tweaking, because that finds files *not on any branch* **ignoring** archival copies of branches. We only want to delete files from *unmerged* branches, which is different.

Related issue: https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/pulls/37

**Comment by jcohenadad** [comment]
thank you @kousu. Not great news i suppose... how about the scenario where we ask students to copy (e.g. via smb/afp on a dedicated folder on our internal duke server: duke:temp/git-annex) the files to be pushed. Then, the "git-annex castle protectors" (nick/alex/julien) will do the syncing? that way, if there is a problem, it's on us 😅

**Comment by kousu** [comment]
I think that's still the best option at the moment.

**Comment by kousu** [comment]
I think we should think about looking into using `git-lfs` with non-Github servers. I know it's possible to set up. It's even possible to keep the main repo on github but the LFS part on non-github servers, that would be cheaper.

**Comment by kousu** [comment]
Oh but git-lfs doesn't support deletion *ever*, so maybe that's no good either.

**Comment by kousu** [comment]
I think we can get close to this workflow with `OWNER_ROLENAME` https://github.com/neuropoly/data-management/issues/53#issuecomment-805453678

I think I'd set `OWNER_ROLENAME="OWNERS";` in `gitolite.rc`, then configure the repo template as

```
# semi-public datasets
repo datasets/..*
    C    = @all
    RW+D = @admins OWNERS
    - master = @all  # master is a protected branch
    RW+  = WRITERS
    R   = @all
```

**Comment by kousu** [comment]
Actually this is what works:

```
# semi-public datasets
repo datasets/..*
           C = @all
        RW+D = OWNERS
    - master = @all
         RW+ = WRITERS
           R = @all
    # make sure @admins own everything
    option default.roles-1  =   OWNERS @admins
    # this line is to glue the legacy single CREATOR into the newer OWNERS group.
    # see https://gitolite.com/gitolite/wild#appendix-1-owner-and-creator
    option default.roles-2  =   OWNERS CREATOR
```

**Comment by kousu** [comment]
Alright this is done. It's documented at https://github.com/neuropoly/data-management/blob/master/internal-server.md#reviewing-pull-requests and permissions are enforced.
