### ISSUE TITLE
Update data in data_axondeepseg_vcu

### ISSUE THREAD

**Issue by Nish228** [neuropoly/data-management#191]
The ADS team received new data from Virginia Commonwealth University (VCU) and proceeded to generate masks for this data to upload on data_axondeepseg_vcu.
Following the instructions in the Neuropoly lab manual, the following changes made to the dataset in the branch nk/update_vcu_data :
1. "ads-derivatives" added to the "derivatives" folder. 
2. New column "original_filename" added to "Samples.tsv" with the original filename added with each sample.
3. Samples and Participated edited to add the new samples. 
4. Six respective samples added 
4.1. sub-21G204
4.2. sub-22G1311
4.3. sub-22G1319
4.4. sub-22G1320
4.5. sub-22G1328
4.6. sub-22G1329

The output of the updation is:
```30 files changed, 27 insertions(+), 6 deletions(-)
 create mode 100644 derivatives/ads-derivatives/sub-21G204/micr/sub-21G204_sample-21G204_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-21G204/micr/sub-21G204_sample-21G204_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-21G204/micr/sub-21G204_sample-21G204_BF_seg-myelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1311/micr/sub-22G1311_sample-22G1311_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1311/micr/sub-22G1311_sample-22G1311_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1311/micr/sub-22G1311_sample-22G1311_BF_seg-myelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1319/micr/sub-22G1319_sample-22G1319_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1319/micr/sub-22G1319_sample-22G1319_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1319/micr/sub-22G1319_sample-22G1319_BF_seg-myelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1320/micr/sub-22G1320_sample-22G1320_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1320/micr/sub-22G1320_sample-22G1320_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1320/micr/sub-22G1320_sample-22G1320_BF_seg-myelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1328/micr/sub-22G1328_sample-22G1328_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1328/micr/sub-22G1328_sample-22G1328_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1328/micr/sub-22G1328_sample-22G1328_BF_seg-myelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1329/micr/sub-22G1329_sample-22G1329_BF_seg-axon.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1329/micr/sub-22G1329_sample-22G1329_BF_seg-axonmyelin.png
 create mode 100644 derivatives/ads-derivatives/sub-22G1329/micr/sub-22G1329_sample-22G1329_BF_seg-myelin.png
 rewrite samples.tsv (100%)
 create mode 100644 sub-21G204/micr/sub-21G204_sample-21G204_BF.tif
 create mode 100644 sub-22G1311/micr/sub-22G1311_sample-22G1311_BF.tif
 create mode 100644 sub-22G1319/micr/sub-22G1319_sample-22G1319_BF.tif
 create mode 100644 sub-22G1320/micr/sub-22G1320_sample-22G1320_BF.tif
 create mode 100644 sub-22G1328/micr/sub-22G1328_sample-22G1328_BF.tif
 create mode 100644 sub-22G1329/micr/22g-13-29_40x4_seg-axon_zf-1.09375.png
 create mode 100644 sub-22G1329/micr/22g-13-29_40x4_seg-axonmyelin_zf-1.09375.png
 create mode 100644 sub-22G1329/micr/22g-13-29_40x4_seg-myelin_zf-1.09375.png
 create mode 100644 sub-22G1329/micr/sub-22G1329_sample-22G1329_BF.tif
```

**Comment by mariehbourget** [comment]
Thanks @Nish228 for updating the dataset. It looks good!

I have a few minor suggestions, I'll let the decision to include them or not to you and @hermancollin:

1. In the `ads_derivatives` folder, it would be good to have a `dataset_description.json` file, similar to the one in `labels` to identified there files as automatic segmentations from ADS, maybe include the model used for the segmentation in the description (see fields that can be add to "GeneratedBy" as needed [here](https://bids-specification.readthedocs.io/en/stable/03-modality-agnostic-files.html#derived-dataset-and-pipeline-description)).
2. I would add the file extensions (ex: `.tif`) in the original filenames in `samples.tsv`.
3. I remember we discussed adding the `species` column in `participants.tsv`, but I don't remember the conclusion. They are rabbits? If that is the case, the species could be `oryctolagus cuniculus` (ref: NCBI Taxonomy [here](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9986))
4. In `sub-22G1329` at the root of the dataset, there are 3 segmentations files that should probably be in derivatives, they are `22g-13-29_40x4_seg-axon_zf-1.09375.png`, `22g-13-29_40x4_seg-axonmyelin_zf-1.09375.png`, `22g-13-29_40x4_seg-myelin_zf-1.09375.png`. They seem to be identical to the files already in derivatives for that subject, I don't know what the difference is, if any.

Let me know if anything is not clear, thanks again!

**Comment by Nish228** [comment]
Thank you so much for the review. 
I have modified the files with respect to the changes mentioned, except for the addition of "GeneratedBy" in `ads_derivatives/dataset_description.json`.
I will modify the json after a confirmation of the model specifications with @hermancollin .

**Comment by hermancollin** [comment]
Thank you for adding this data @Nish228. You said you incorporated 3 of the changes Marie-Hélène suggested but I don't see these on your branch. Are you sure you pushed your modifications?

**Comment by hermancollin** [comment]
@Nish228 thank you for adding these changes. 
- We still need to add the "GeneratedBy". The URL to the model is https://github.com/axondeepseg/model_seg_rabbit_axon-myelin_bf
- Also we need JSON sidecars for every image

**Comment by hermancollin** [comment]
@Nish228 thank you for your help. I incorporated the changes discussed and merged the branch.
