### ISSUE TITLE
Missing label 2 for `twh` subjects in `sct-testing-large`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#198]
Many `labels-disc-manual.nii.gz` files for `sub-twh*` subjects located under git-annex `sct-testing-large/derivatives/labels` have a missing label `2`.

For example:

```
$ cd sct-testing-large/derivatives/labels
$ sct_label_utils -i sub-twh002/anat/sub-twh002_T2w_labels-disc-manual.nii.gz -display

--
Spinal Cord Toolbox (git-sb/3733-bring-metrics-to-pam50-82e1b9fb7540e681a942abe5a41b83989c9aa3dc)

sct_label_utils -i sub-twh002/anat/sub-twh002_T2w_labels-disc-manual.nii.gz -display
--

Position=(125,215,34) -- Value= 1
Position=(127,166,34) -- Value= 3
Position=(124,142,34) -- Value= 4
Position=(127,117,34) -- Value= 5
Position=(127,93,34) -- Value= 6
Position=(128,69,34) -- Value= 7
Position=(128,46,34) -- Value= 8
Position=(130,18,34) -- Value= 9
Position=(153,230,34) -- Value= 49
All labels (useful syntax):
125,215,34,1:127,166,34,3:124,142,34,4:127,117,34,5:127,93,34,6:128,69,34,7:128,46,34,8:130,18,34,9:153,230,34,49
```

This, in practice, leads to a missing C2 vertebral level after vertebral labeling:
![image](https://user-images.githubusercontent.com/39456460/208165121-9e1e60c5-34df-4956-8f3b-62fe00b3afc3.png)

After running a loop across all subjects, I found that 63 subjects have a missing label 2.

<details><summary>CLI output</summary>

```
$ cd sct-testing-large/derivatives/labels
$ for sub in sub-twh0*;do label2=$(sct_label_utils -i ${sub}/anat/${sub}_T2w_labels-disc-manual.nii.gz -display | grep "Value= 2");if [[ $label2 == "" ]];then echo $sub;fi;done
sub-twh002
sub-twh010
sub-twh024
sub-twh025
sub-twh026
sub-twh028
sub-twh029
sub-twh030
sub-twh031
sub-twh032
sub-twh033
sub-twh034
sub-twh035
sub-twh036
sub-twh037
sub-twh038
sub-twh039
sub-twh040
sub-twh041
sub-twh042
sub-twh044
sub-twh045
sub-twh046
sub-twh047
sub-twh048
sub-twh049
sub-twh050
sub-twh051
sub-twh052
sub-twh053
sub-twh054
sub-twh055
sub-twh056
sub-twh057
sub-twh058
sub-twh059
sub-twh060
sub-twh061
sub-twh062
sub-twh063
sub-twh064
sub-twh065
sub-twh066
sub-twh067
sub-twh069
sub-twh070
sub-twh071
sub-twh072
sub-twh073
sub-twh074
sub-twh075
sub-twh076
sub-twh077
sub-twh079
sub-twh080
sub-twh081
sub-twh082
sub-twh083
sub-twh084
sub-twh086
sub-twh087
sub-twh088
sub-twh090
```
</details>

The `labels-disc-manual.nii.gz` file is missing completely in the following 5 subjects:

```
sub-twh027
sub-twh043
sub-twh068
sub-twh085
sub-twh089
```

**Comment by jcohenadad** [comment]
great catch @valosekj ! Thank you for reporting it 🙏  This might have caused some issues in our training/evaluation of disc detection models

**Comment by valosekj** [comment]
I corrected the `labels-disc-manual.nii.gz` files in `3344772dcec88dacc8caca8d7595c0e2047ed4df` commit for all above mentioned subjects except of the following three:

- `sub-twh043_T2w.nii.gz` - bad image quality
- `sub-twh068_T2w.nii.gz `- bad image quality
- `sub-twh085_T2w.nii.gz` - severe scoliosis 

My branch is named `jv/198-fix_labels-disc_files_for_twh_subjects`. I also updated the `README.txt`.

The QC is attached. @sandrinebedard, could you please double-check the QC? Thanks!

[qc_corr_20221216153819.zip](https://github.com/neuropoly/data-management/files/10249422/qc_corr_20221216153819.zip)

**Comment by sandrinebedard** [comment]
QC Looks good! For the three menitonned subjects, would it be better to remove the disc_file is it is missing a label in it?

**Comment by valosekj** [comment]
> QC Looks good! For the three menitonned subjects, would it be better to remove the disc_file is it is missing a label in it?

Yeah! It makes sense. `labels-disc-manual.nii.gz` for these 3 subjects do not exist in the `main`. And I mistakenly added them when running a manual correction script.

@mguaypaq could you please `git rm` for `labels-disc-manual.nii.gz` and `labels-disc-manual.json` files for the three above-mentioned subjects from my branch before the merge (and maybe add info about them to README)? (I tried to do it in my local branch, but I somehow introduced also some unwanted changes to my local branch which I don't want to push). Thank you!

**Comment by mguaypaq** [comment]
Merged to master.

@valosekj it looks like you already had a commit to `git rm` the files for `sub-twh043`, so I amended it to also remove the files for `sub-twh068` and `sub-twh085`. For the README, it already contained a link to this issue, and these removed files were originally not present on master anyway, so I didn't modify it. But I did mention the three subjects in the commit message:
```
commit b43bf48c6747f4e360cf22817b3ca194b90a82d4 (HEAD -> master, origin/master, origin/HEAD, jv/198-fix_labels-disc_files_for_twh_subjects)
Author: valosekj <jan.valosek@upol.cz>
Date:   Sat Dec 17 07:36:18 2022 -0500

    Remove labels-disc-manual for 3 subjects
    
    Mistakenly added in commit 3344772dcec88dacc8caca8d7595c0e2047ed4df.
    
    These subjects are excluded for the following reasons:
    
    * sub-twh043_T2w.nii.gz - bad image quality
    
    * sub-twh068_T2w.nii.gz - bad image quality
    
    * sub-twh085_T2w.nii.gz - severe scoliosis
```

**Comment by valosekj** [comment]
Thanks @mguaypaq! 🙏🏻
