### ISSUE TITLE
Disaster Plan

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#20]

**Comment by kousu** [comment]
Reminder (to selves) that this is still an unsolved problem

**Comment by kousu** [comment]
This was handled in https://github.com/neuropoly/computers/issues/65: I used [restic](restic.readthedocs.io/) and put one backup on s3.amazonaws.com in Montreal, and another on narval.computecanada.ca, also in Montreal. It's not yet reproducible but it's enough to count this finished.

**Comment by jcohenadad** [comment]
Wonderful, thank you!
