### ISSUE TITLE
`canproco` - add EDSS score to `participants.tsv`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#200]
I added EDSS score to the `datasets/canproco/participants.tsv` in the branch `jv/add_edss_score` and commit `634bb1ffef7ad76ad1b1a6b09a8dad384115bf70`. Since this EDSS score corresponds to the `ses-M0`, I named the column as `edss_M0`.

For healthy controls (`HC`), I added `n/a`.

For one MS patient (`sub-van175`), the EDSS score is pending. (I added `n/a` for now)

**Comment by mguaypaq** [comment]
Can you add an entry to `participants.json` to describe the new column?

**Comment by valosekj** [comment]
> Can you add an entry to `participants.json` to describe the new column?

Thank you for this catch! 
`edss_M0` added to `participants.json` in `8307d16a0833ca07528da64342b7d355caba4f72`.

**Comment by mguaypaq** [comment]
I added a missing comma to the JSON file (on the preceding line), and now bids-validator is reasonably happy. It's still complaining about missing column descriptions for `pathology` and `phenotype`, but I guess that should be done in #187.

Merged into master.
