### ISSUE TITLE
Added missing derivatives for `sci-zurich` dataset

### ISSUE THREAD

**Issue by naga-karthik** [neuropoly/data-management#201]
**Issue 1:** Six subjects in the sci-zurich dataset did not have the corresponding `_lesion-manual.nii.gz` files as these subjects do not have any lesions. However, for uniformity, we would like to have empty label files explaining the absence of lesions. 

**Solution:** Empty label files have been added for these subjects. The screenshot below shows the addition of derivative files. 

<img width="762" alt="Screen Shot 2023-01-10 at 11 58 35 AM" src="https://user-images.githubusercontent.com/53445351/211614652-5554ac5f-1509-432b-9265-b5b3afad9a63.png">

**Issue 2:** While the data for a few subjects exist, their entries are not included in the `participants.tsv` file. This might erroneously leave out subjects if the data are retrieved based on the entries in the `.tsv` file.

**Solution:** Updated the participants.tsv file by entering the missing subjects. The precise meta-data for these subjects is unknown at the moment, hence I used `X` and `00` to denote missing sex and age meta-data. For example, 

<img width="142" alt="Screen Shot 2023-01-10 at 12 05 24 PM" src="https://user-images.githubusercontent.com/53445351/211616057-228dbe98-5ebc-4da4-b4fe-92ca1172ec59.png">

These changes can be found under my branch `nk/add_missing_derivatives`.

**Comment by jcohenadad** [comment]
@naga-karthik can you please get rid of the `^M` character:

```console
diff --git a/participants.tsv b/participants.tsv
index a937137..a27cad1 100644
--- a/participants.tsv
+++ b/participants.tsv
@@ -22,6 +22,7 @@ sub-zh20      F       23
 sub-zh21       M       67
 sub-zh22       F       38
 sub-zh23       F       59
+sub-zh24       X       00^M
 sub-zh25       M       47
 sub-zh26       M       72
 sub-zh27       F       77
@@ -46,6 +47,7 @@ sub-zh46      F       67
 sub-zh47       M       22
 sub-zh48       M       77
 sub-zh49       M       41
+sub-zh50       X       00^M
 sub-zh51       M       19
 sub-zh52       M       70
 sub-zh53       M       30
@@ -60,12 +62,16 @@ sub-zh61    M       32
 sub-zh62       M       52
 sub-zh63       F       44
 sub-zh64       M       53
+sub-zh65       X       00^M
 sub-zh66       F       63
```

**Comment by jcohenadad** [comment]
also, if you don't know the answer, use `n/a` instead of `X` or `00`.

**Comment by naga-karthik** [comment]
Just changed the unknown values to `n/a` in the latest commit. 

As for the `^M`, it is strange because I didn't see that when I updated the `.tsv` file on my end. Then I searched for it and apparently it's a feature of `git diff` denoting newline as seen [here](https://stackoverflow.com/questions/1889559/make-git-diff-ignore-m). Maybe running `git diff -b` will not show this extra character?

**Comment by naga-karthik** [comment]
The extra newline character issue should also be fixed now!

**Comment by jcohenadad** [comment]
> As for the ^M, it is strange because I didn't see that when I updated the .tsv file on my end.

sorry my bad then!

**Comment by jcohenadad** [comment]
looks good! can I merge?

**Comment by jcohenadad** [comment]
@naga-karthik just for my understanding:

you wrote:
> As for the ^M, it is strange because I didn't see that when I updated the .tsv file on my end. Then I searched for it and apparently it's a feature of git diff denoting newline as seen [here](https://stackoverflow.com/questions/1889559/make-git-diff-ignore-m). Maybe running git diff -b will not show this extra character?

and then:
> The extra newline character issue should also be fixed now!

So, was there an issue or not? and if so, how did you fix it?

**Comment by naga-karthik** [comment]
Ah yes, sorry about the confusion, I used these commands as suggested by @valosekj to get rid of the `^M` character. 
```
$ mv participants.tsv participants_backup.tsv
$ tr -d '\r' <participants_backup.tsv > participants.tsv
```

**Comment by jcohenadad** [comment]
> looks good! can I merge?

**Comment by naga-karthik** [comment]
Yes, please merge it

**Comment by jcohenadad** [comment]
done! thank you @naga-karthik 

```console
julien-macbook:~/data.neuro/sci-zurich $ gl
b644d4527e81def21aa69316992fa54aac5d83d0 (HEAD -> master, origin/master, origin/HEAD) removed newline characters
6c79a2c5331f6ffede9d7b7d0038a4cf408f5b54 replace unknown metadata with n/a
4992691c16dae7d22244ef331aae8d75a99c8b94 added missing subjects
f579fad2580336f5ff6a53a64a63d4a389bbeb59 added missing derivative files
5cdccf6f6197a50443775f91047d1692513c5254 add additional data
ceebe5c465a8d421417282cd622a70d13c9db429 (origin/af/change_dataset_description) update dataset_description.json
d823215a0f5b432eb0c136729982d6a32f80e262 (origin/synced/master, origin/nk/manual_seg) added manual seg for 3 subjects & updated README
4ef05bf0b70c04490cd73f433cac4f5f43e5dac3 Added info in README
de32973f7c55de2d2ced770fea74c5e3c00cfadd Initial data
3a2ad33b2feb5ed3969d067039d289f1fcbea797 Configure git-annex
87d0cb15bac4bd3c332501becd73e3847cb5ba5e Initial commit
```
