### ISSUE TITLE
`canproco` - ivadomed misses "PipelineDescription" in `dataset_description.json`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#205]
Currently, `data.neuro.polymtl.ca/canproco/dataset_description.json` looks like:

```
{
    "Name": "CanProCo BIDS Dataset",
    "BIDSVersion": "1.2.0",
    "Notes": "Multi-site dataset"
}
```

But ivadomed also requires `PipelineDescription` field, like:

```
{
    "Name": "CanProCo BIDS Dataset",
    "BIDSVersion": "1.2.0",
    "Notes": "Multi-site dataset",
    "PipelineDescription": {
        "Name": "CanProCo"}
}
```

I will add this field to `data.neuro.polymtl.ca/canproco/dataset_description.json` and also to [intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#dataset-description-json).

**Comment by jcohenadad** [comment]
> But ivadomed also requires PipelineDescription field, like:

where is that requirement listed? and how useful is it to have the name "CanProCo" as a pipeline name? I'm pretty sure that in 10y from now, a new student looking at the dataset and seeing "CanProCo" won't be very informative. Why not a URL pointing to the pipeline instead? with a specific version, etc.

**Comment by valosekj** [comment]
Okay, it seems that the `PipelineDescription` field was required by the older ivadomed version (2.9.1). After updating to the latest ivadomed version (master branch), ivadomed works with the original `dataset_description.json`:

```
{
    "Name": "CanProCo BIDS Dataset",
    "BIDSVersion": "1.2.0",
    "Notes": "Multi-site dataset"
}
```
