### ISSUE TITLE
`canproco` - add automatically generated T2w SC segmentation

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#206]
Currently, `data.neuro.polymtl.ca/canproco/derivatives` contains manually corrected SC T2w segmentations for 45 subjects (added in [this issue/PR](https://github.com/neuropoly/data-management/issues/186)).

Within the brach `jv/add_automatic_t2w_seg_to_derivatives` in `ceca70d1c357007b4221df9d85c02887dd79706c` commit, I added SC T2w segmentations also for the remaining 405 subjects. These segmentations were generated automatically by `set_deepseg_sc` and visually checked.

Having all SC T2w segmentations (i.e., manually corrected and automatically generated) in the `derivatives` folder allows easy download of these segmentations, for example, for purposes of DL model training.

I also updated `README` in `046f35e361aca973a5e6899ea77c0e5b4358af9e` commit to address [confusing file names between manually corrected derivatives and native data](https://github.com/neuropoly/data-management/issues/197#issuecomment-1353372577).

**Comment by mguaypaq** [comment]
After a quick in-person discussion: it looks like the processing script made an error on `sub-cal209`, because this subject [has no T2w images](https://github.com/ivadomed/canproco/blob/main/etc/exclude.yml), so it instead copied the STIR and T2star images for this subject to the derivatives. I'll add a commit to remove these spurious files, and merge into master.

**Comment by mguaypaq** [comment]
Done!

**Comment by valosekj** [comment]
> After a quick in-person discussion: it looks like the processing script made an error on `sub-cal209`, because this subject has no T2w images, so it instead copied the STIR and T2star images for this subject to the derivatives. I'll add a commit to remove these spurious files, and merge into master.

Thank you! 👍🏻
