### ISSUE TITLE
`canproco` - split 4D MT images

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#211]
This issue addresses https://github.com/ivadomed/canproco/issues/21. The branch name is `jv/split_4D_MT_images`.

Specifically, I split 4D MT (`acq-MT_MTS.nii.gz`) images for Calgary subjects into three 3D volumes (`acq-MTon_MTS`, `acq-MToff_MTS`, `acq-T1w_MTS`).

Changes within the `jv/split_4D_MT_images` branch:
- add the script I used under `code` folder.
- add 552 MT files (92 subjects * 3 nii.gz files * 3 .json files)
- removed 184 `acq-MT_MTS` json and .nii.gz files (92 subjects * 2 files)
- add info about missing data to README
- rename README to README.md

Note: `sub-cal161` has no MT data. I added this information to [canproco/exclude.yml](https://github.com/ivadomed/canproco/blob/main/etc/exclude.yml) as well as to git-annex/canproco/README.

**Comment by mguaypaq** [comment]
I recently came across the issue [spine-generic/data-multi-subject#116](https://github.com/spine-generic/data-multi-subject/issues/116), which says that these names are maybe no longer standard? Although I don't know the details, so maybe this is a different context and/or not applicable here.

**Comment by valosekj** [comment]
> I recently came across the issue [spine-generic/data-multi-subject#116](https://github.com/spine-generic/data-multi-subject/issues/116), which says that these names are maybe no longer standard? Although I don't know the details, so maybe this is a different context and/or not applicable here.

You are absolutely right! I meant to rename MT images in a consequent branch. (I am using the "old" naming here because the splitting of 4D images is related only to Calgary. And I wanted to have consistent filenames across the whole dataset)

**Comment by mguaypaq** [comment]
Ok, the changes look fine, `git annex get` works, and `bids-validator` is happy. Merged into master.

**Comment by valosekj** [comment]
Thank you! 👍🏻

**Comment by valosekj** [comment]
Based on https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4024, I recreated the `acq-MTon_MTS`, `acq-MToff_MTS`, `acq-T1w_MTS` images using `-split t` instead of `-keep-vol`.

Specifically:

```
# checkout to commit before deleting 4D `acq-MT_MTS.nii.gz` images
git checkout f47540d74
# create a new branch
git checkout -b jv/split_4D_MT_images-fix
```

Then I pushed three commits to branch `jv/split_4D_MT_images-fix`:

- `18b792f3f239b25e49cd40f89cac4971bf8035a2` - "code/split_4D_MT.sh - switch from `-keep-vol` to `-split t`"
- `9d58ff24e0efa0dafb3e25667a5df61fb552b417` - "Add acq-MTon_MTS, acq-MToff_MTS, and acq-T1w_MTS json and nii.gz files for sub-cal* created using `-split t`"
- `ea3d0d794dc8d76d7cbd5504fa4459447455953f` - "Remove acq-MT_MTS json and .nii.gz files for sub-cal*"

@mguaypaq could you please merge `jv/split_4D_MT_images-fix` branch to master?

Sidenote:
When running `git log`, I noticed that the commit text closed in "`" is not shown. Probably, the use of these quotation marks in commit messages is not appropriate.

**Comment by mguaypaq** [comment]
Ok, the fixed images are now merged into master on the server:
* I rewrote the commit messages on the new `jv/split_4D_MT_images-fix` branch to preserve the \`-quoted strings (it was a problem with the shell, not with commit messages containing \`-style quotes).
* I force-pushed these updated commits to the server on the `jv/split_4D_MT_images-fix` branch, so you may see some local divergence on your version of that branch.
* I reverted the relevant commits from the old `jv/split_4D_MT_images` branch (to avoid merge conflicts), then merged the new `jv/split_4D_MT_images-fix` branch into master. This should _not_ cause any local divergence with your version of master.
* `git annex get` and `bids-validator` are both happy, so I pushed this to the server.

**Comment by valosekj** [comment]
> Ok, the fixed images are now merged into master on the server:
> 
> * I rewrote the commit messages on the new `jv/split_4D_MT_images-fix` branch to preserve the `-quoted strings (it was a problem with the shell, not with commit messages containing `-style quotes).
> * I force-pushed these updated commits to the server on the `jv/split_4D_MT_images-fix` branch, so you may see some local divergence on your version of that branch.
> * I reverted the relevant commits from the old `jv/split_4D_MT_images` branch (to avoid merge conflicts), then merged the new `jv/split_4D_MT_images-fix` branch into master. This should _not_ cause any local divergence with your version of master.
> * `git annex get` and `bids-validator` are both happy, so I pushed this to the server.

Thank you @mguaypaq! 💯  Everything seems to be working for me!
