### ISSUE TITLE
`spine-generic processed` is a duplicate of `spine-generic/data-multi-subject`

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#212]
## Description 
We have decided to stop working with the spine-generic-processed dataset since there was conusion on where to keep the derivatives  (in data-multi-subject or spine-generic-processed). All the derivatives in spine-generic-processed were transfered into data-multi-subject (https://github.com/spine-generic/data-multi-subject/pull/123)

Related issues:
* https://github.com/spine-generic/data-multi-subject/issues/94
* https://github.com/spine-generic/data-multi-subject/issues/121

I propose to remove the spine-generic-processed dataset from our internal server to avoide confusion for futur students.

**Comment by sandrinebedard** [comment]
@jcohenadad what is your opinion on this?

**Comment by jcohenadad** [comment]
I agree, this is an excellent initiative!

**Comment by sandrinebedard** [comment]
@mguaypaq you can delete the dataset! I double checked we don't need anything from it anymore.

**Comment by mguaypaq** [comment]
Done!
