### ISSUE TITLE
Add lesion segmentation in `canproco` 

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#213]
## Description

63 manual lesion segmentations for the Edmonton site on the PSIR images are added uner the branch `sb/add-manual-lesions-psir`

**Comment by sandrinebedard** [comment]
We can wait before merging until we have the lesions for all the sites!

**Comment by sandrinebedard** [comment]
We now have all the lesion segmentations from all sites, it is ready for review @mguaypaq !
Thank you @mchen1110 !

**Comment by mguaypaq** [comment]
Looks good, merged into master.
