### ISSUE TITLE
`inspired` - add clinical data

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#216]
I added clinical data to `inspired` dataset within the `jv/add_clinical_data` branch in commit `4bc02fe61f24c8b6560db23ce8890fbc1e86ea30`. 

`bids-validator` seems to be satisfied.

**Comment by mguaypaq** [comment]
Nitpick: the ages used to be integers, now they are floating point numbers (for example, `42` -> `42.0`). Ping me once the script is fixed and I'll merge to master.

**Comment by valosekj** [comment]
> Nitpick: the ages used to be integers, now they are floating point numbers (for example, `42` -> `42.0`). Ping me once the script is fixed and I'll merge to master.

Should be fixed in `ee5ddd845054e059d53baf1fd6ce7d02598f4163` commit.

**Comment by mguaypaq** [comment]
Thanks! Merged into master.
