### ISSUE TITLE
`dcm-zurich` - add data

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#218]
I added initial data to `data.neuro.polymtl.ca:datasets/dcm-zurich` within the `jv/add_files` branch in `6d3438da18c81b45bc61dcfd2e86752e2066167d` commit.

Details about the BIDSification are available at https://github.com/neuropoly/data-management/pull/217

---

`bids-validator` is reasonably happy; it has just three complaints:

```
1: [WARN] Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		./sub-250791/anat/sub-250791_T1w.json
			Evidence: Subject: sub-250791; Missing file: sub-250791_T1w.json
...
```

This is fine. Not all subjects have T1w images (see README.md for details).

```
2: [WARN] Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
		./sub-250791/anat/sub-250791_acq-axial_T2w.nii.gz
...
```

This is also fine. We used the stitching to combine two axial images (see README.md for details). This resulted in a different number of slices for the stitched images across subjects.

```
3: [WARN] The Authors field of dataset_description.json should contain an array of fields - with one author per field. This was triggered because there are no authors, which will make DOI registration from dataset metadata impossible. (code: 113 - NO_AUTHORS)
```

We can probably ignore this one?

**Comment by mguaypaq** [comment]
Great! I added the following `.bids-validator-config.json`, and merged to master:
```json
{"ignore": [
    "INCONSISTENT_SUBJECTS",
    "INCONSISTENT_PARAMETERS",
    "NO_AUTHORS"]}
```
I had to rewrite your commit with the data to make sure it was git-annexed, so please delete your branch `jv/add_data` locally to make sure the data stays annexed.
