### ISSUE TITLE
`dcm-zurich` - add sub-821908_acq-sagittal_T2w

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#219]
The [curation script](https://github.com/neuropoly/data-management/blob/f6bb8d14fe10d412d5b45a53255b8af6d8b41ebe/scripts/curate_dcm-zurich.py) missed the sagittal T2w image for `sub-821908`.

I pushed this image to git-annex within branch `jv/add_sub-821908_acq-sagittal_T2w` and commit `efecb6ee5e618a6acf6f9077a7efd550a3dff0d7`

**Comment by mguaypaq** [comment]
Looks good, merged into master.
