### ISSUE TITLE
Internal server (git+ssh://data.neuro.polymtl.ca)

### ISSUE THREAD

**Issue by kousu** [neuropoly/data-management#22]
I am deploying a git server on poly's internal infrastructure. This is cheaper, and faster (bandwidth-wise) than paying Amazon or Github for hosting the large datasets we experiment on, and safer for our datasets with privileged medical data.

**Comment by kousu** [comment]
I removed `"create"` from the `ENABLED` list, from feedback from @joshuacnewton. That leaves only two ways to make a new repo:

1. someone ssh's into the server and makes it there directly
2. `git push`

**Comment by joshuacwnewton** [comment]
> I removed "create" from the ENABLED list, from feedback from @joshuacwnewton:

Just to clarify, I suggested this because (unless I'm missing something), regular users weren't able to `ssh git@data.neuro.polymtl.ca create` anyway:

```
joshua@XPS-15-9560:~$ ssh git@data.neuro.polymtl.ca create test-permissions
FATAL: repo already exists or you are not authorised to create it
```

Or, was I supposed to do ` ssh git@data.neuro.polymtl.ca create datasets/<repo-name>` because that's the directory I have permissions for?

**Comment by kousu** [comment]
This is in production now and has been for a while.
