### ISSUE TITLE
`dcm-zurich` - add QCed T2w ax SC segmentations

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#221]
This is a follow-up of https://github.com/neuropoly/data-management/issues/220. 
I added automatically generated (by `sct_deepseg_sc`) and QCed spinal cord segmentation for axial T2w images for 90 subjects in `jv/add_QCed_T2w_ax_SC_seg` branch.

Footnote:
Now, axial T2w SC seg is available for 135 subjects (45 in https://github.com/neuropoly/data-management/issues/220 + 90 in this issue) from 140. Two subjects do not have axial T2w at all --> no SC seg can be obtained. The remaining 3 subjects will be investigated.

**Comment by mguaypaq** [comment]
Merged into master.
