### ISSUE TITLE
`dcm-zurich` - remove automatically generated disc labels from `derivatives`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#227]
It turned out that in the case of disc labels, we should store **_only_** manually corrected disc labels (located on the posterior tip of each disc, example [here](https://github.com/sct-pipeline/dcm-metric-normalization/issues/10#issue-1634860919)) under `derivatives`. 

@mguaypaq, could you please remove `0305a44f46a512067ceb315fd20e19a2eb684650` and `a10ac70c6771b1c7a5cb76143851c04931100434` commits, which added automatically generated and visually inspected disc labels (located in the middle/center of the spinal cord, example [here](https://github.com/sct-pipeline/dcm-metric-normalization/issues/10#issue-1634860919)) for T2w sag images for 65 subjects? 

Context: https://github.com/sct-pipeline/dcm-metric-normalization/issues/10

**Comment by mguaypaq** [comment]
Done, I added a new commit to `master` with the following description:
```
Remove automatically generated and visually inspected disc labels for T2w sag images for 65 subjects

It turned out that in the case of disc labels, we should store only manually corrected disc labels under derivatives.
This reverts commits 0305a44f46a512067ceb315fd20e19a2eb684650 and a10ac70c6771b1c7a5cb76143851c04931100434.

These 7 subjects, which had manually corrected disc labels added after these two commits, have been kept:

sub-582241
sub-836392
sub-839057
sub-856307
sub-861253
sub-864639
sub-869695
```
So 116 files are deleted (which is 2 files (.json and .nii.gz) times (65 - 7) subjects).
