### ISSUE TITLE
`dcm-zurich` add clinical data to participants.tsv

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#228]
We received some clinical data from the dcm-zurich cohort. Here are the received feilds:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sb199/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

record_id | age | sex | height | weight | previous_surgery | date_of_surgery | therapeutic_decision | surg_date | mri_date | mri_type | c2_stenosis_no_yes | c2_myelopathy | c3_stenosis_no_yes | c3_myelopathy | c4_stenosis_no_yes | c4_myelopathy | c5_stenosis_no_yes | c5_myelopathy | c6_stenosis_no_yes | c6_myelopathy | c7_stenosis_no_yes | c7_myelopathy | myelopathy_any segment | number_stenosis | maximum_stenosis
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Here is the information provided in the email from Markus:

>Sex: 1=female, 2=male
Therapeutic_decision: 1=conservative; 2=operative
mri_type: 1=Skyra; 2 =Prisma
Maximum_stenosis: 2=segment C3/4; 3=C4/5; 4=C5/6; 5=C6/7; 6=C7/T1
Number_stenosis: number of stenotic classified segments 

</body>

</html>

Here are a few points to discuss before adding it to `participants.tsv`

**1. record_id correspondance with sub-XXX**
The `record_id` goes from 1 to 158, while in the image dataset, we only have 140 subjects and id numbers differ (6 number id)
--> Question to ask to Markus

**2. Do we consider `maximum_stenosis` as our maximum compression?**
--> Question to ask Markus

**3. Change 0/1 fields or 1/2 fields for specific value/word**
Example: change `mri_type` with Skyra and Prisma direclty. or yes/no for other cases.

**4. Level correspondance for maximum stenosis**
Change level number:  2=segment C3/4; 3=C4/5; 4=C5/6; 5=C6/7; 6=C7/T1

**5. Change levels to disc**
Does C2 refer to the disc C2/C3? etc.

@jcohenadad @valosekj do you have other comments about the received data?

**Comment by jcohenadad** [comment]
About the fields: "c2_stenosis_no_yes, c2_myelopathy, c3_stenosis_no_yes, etc." these are a lot of columns! Do we have another way to encode stenosis, eg: "stenosis={c2, c3, c4, etc.}". Ideally we would use a standardized way to do it across our various projects in the lab. Eg: for the CanProCo project, we also have to encode lesion location and number, so that seems like a similar problem.

**Comment by valosekj** [comment]
> 5. Change levels to disc
Does C2 refer to the disc C2/C3? etc.

I think so. For example, record_id=2 has maximum_stenosis=4. This refers to C5/6 (based on the information provided in the email from Markus). This then corresponds with the column c5_stenosis_no_yes=1. Which in turn means that C5 refers to the C5/6 disc.

> Do we have another way to encode stenosis, eg: "stenosis={c2, c3, c4, etc.}". 

This convention sounds good! For example something like this?


| participant_id | stenosis      | myelopathy | MCL     |
|----------------|---------------|------------|---------|
| sub=001        | C6/C7  | C6/C7      | C6/C7   |
| sub=002        | C2/C3, C3/C4  | C3/C4      | C3/C4   |

> Ideally we would use a standardized way to do it across our various projects in the lab. Eg: for the CanProCo project, we also have to encode lesion location and number, so that seems like a similar problem.

Great idea! Grouping several columns under a single column could be generally applied also to other pathologies (MS lesions, SCI lesions, etc.). Example:

| participant_id | lesion      |
|----------------|---------------|
| sub=001        | C3  |
| sub=002        | C4, C6-C7  |

(`C6-C7` would represent lesion spreading across both segments C6 and C7)

**Comment by sandrinebedard** [comment]
I updated the `participants.tsv` and `participants.json` and added the script to merge the clinical data in the branch `sb/update-participants-tsv`.

@valosekj @jcohenadad  and @mguaypaq can you take a look? thanks!

**Comment by valosekj** [comment]
> I updated the `participants.tsv` and `participants.json` and added the script to merge the clinical data in the branch `sb/update-participants-tsv`.
> 
> @valosekj @jcohenadad and @mguaypaq can you take a look? thanks!

Thank you Sandrine! LGTM!

Just one tiny nitpick about the column names. Maybe we could rename `mri_date` to `date_of_scan` and `mri_type` to `manufacturers_model_name`. To be in line with [data-multi-subject/participants.tsv](https://github.com/spine-generic/data-multi-subject/blob/master/participants.tsv). Also, we could add column `manufacturer` explicitly mentioning Siemens.

**Comment by mguaypaq** [comment]
On my end this looks reasonable: the script looks fine, there are no new or modified git-annexed files, and bids-validator is still happy. Let me know if/when you rename the columns as @valosekj suggested, and I'll merge into master.

**Comment by sandrinebedard** [comment]
Everything is updated with the renamed columns!

**Comment by mguaypaq** [comment]
Merged into master!
