### ISSUE TITLE
Manual correction of axial discs labels in `dcm-zurich`

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#229]
## Description

New manually corrected discs labels for axial images were added in the branch `nm/add_manual_corr_axial_labels` in `dcm-zurich`. Only subjects that needed corrections were added in this push, other should come in another push.

**Comment by mguaypaq** [comment]
After in-person discussion: maybe we should wait until more corrections are done before merging the branch? Unclear. I'll wait for a ping on this issue before merging to master.

**Comment by sandrinebedard** [comment]
We can merge, after discussion, we will only include the manual corrections (at the posterior tip of the disc) for now, since automatic labels are at the center of the cord.

**Comment by mguaypaq** [comment]
Ok, merged into master.

I had to rewrite the commit, because the image files were directly in git, instead of git-annex. Everything's OK now, but please don't re-use the branch `nm/add_manual_corr_axial_labels`.
