### ISSUE TITLE
Add compression labels to derivatives `dcm-zurich`

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#230]
## Description

I added the compression labels (on the axial image) into the derivatives according to the stenosis reported by clinicians (in the participants.tsv) for the `dcm-zurich` database . I updated the `participants.tsv` according to the comments by Markus Hupp ([see presentation](https://docs.google.com/presentation/d/1mO2cwqrWSDA9aiov4pUzIPgA01OFOXdjDAwEqwoVjig/edit#slide=id.g22bf5f6d901_6_119))

Modifications are under the branch `sb/add-compression-labels`.

**Comment by mguaypaq** [comment]
I rebased onto master, checked that `git annex get` and `bids-validator .` are both happy, and merged into master.
