### ISSUE TITLE
Add fixed vertebral labelinng in `dcm-zurich`

### ISSUE THREAD

**Issue by sandrinebedard** [neuropoly/data-management#231]
# Description

This PR adds a new manual disc labeling for `sub-847751` under `sb/fix-vertebral-label` regarding this [issue](https://github.com/sct-pipeline/dcm-metric-normalization/issues/12).

Updated disc labeling:

![image](https://user-images.githubusercontent.com/71230552/232572148-314efba6-e48f-4d8e-bf1b-5a724f001a3d.png)

The qc report is attached.
[qc_corr_20230417135748.zip](https://github.com/neuropoly/data-management/files/11254081/qc_corr_20230417135748.zip)

**Comment by mguaypaq** [comment]
Rebased onto master and merged :heavy_check_mark:
