### ISSUE TITLE
`dcm-zurich-lesions` - add derivatives

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#233]
In the `jv/add_compression_labels` branch, I added manual SC segmentation and disc labels to `dcm-zurich-lesions` dataset.

I also fixed sform and qform mismatch (see [here](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/3992#issuecomment-1518633699)) for sub-10 and sub-16.

**Comment by mguaypaq** [comment]
Merged into master!
