### ISSUE TITLE
Add SC Segmentations to sci-zurich

### ISSUE THREAD

**Issue by naga-karthik** [neuropoly/data-management#236]
The sci-zurich dataset does not originally have SC segmentations. In order to train a [region-based nnUNet](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/region_based_training.md) model, it was discussed that having both SC seg. and lesion seg. might be useful. Hence, this issue add SC segmentations to this dataset. 

`sct_deepseg_sc` was used for getting automated segmentations. @valosekj visually QC'd all the segmentations and flagged the wrong ones (n=40; see attached YML file). Both @valosekj and I did the manual corrections. Both the automatically generated and manually corrected segmentations can be found under the branch `jv/add_sc_seg`. 

@mguaypaq, could you please merge it to main? Thanks in advance!

[qc_fail_sci-zurich_2023-04-28.yml.zip](https://github.com/neuropoly/data-management/files/11415821/qc_fail_sci-zurich_2023-04-28.yml.zip)

**Comment by valosekj** [comment]
Hold on with the merge! @naga-karthik and I have decided to go also through the automatically generated segmentations to double-check their quality.

**Comment by mguaypaq** [comment]
Ok, you can ping me on this issue when you're ready for the merge.

**Comment by valosekj** [comment]
Closing since solved within https://github.com/neuropoly/data-management/issues/238
