### ISSUE TITLE
Correct SC seg - `sci-zurich`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#238]
@naga-karthik and I went through all `sci-zurich` subjects and corrected T2w sag spinal cord segmentations if necessary.

We split the work:
- I corrected the first half of the dataset (n=51 needed corrections) within `jv/add_sc_seg` branch and `f49ccc7ae4ab977c0ec0ffbbf0a5a2d697192fa4` commit
- @naga-karthik corrected the second half of the dataset. After some troubles when trying to rebase `jv/add_sc_seg`, we decided together with @mguaypaq to push changes to a new branch: `nk/wip`

Both branches can now be merged into master.

**Comment by mguaypaq** [comment]
Ok:
- The rebasing of `nk/wip` onto `jv/add_sc_seg` worked fine for me.
- Both `git annex get` and `bids-validator .` are happy.
- This is all merged into `master`.
- I cleaned up the old branches from the server.
