### ISSUE TITLE
New dataset `whole-spine`

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#241]
## Description

A new dataset called `whole-spine` is now available on `data.neuro.polymtl.ca:datasets/whole-spine` on the git-annex branch `nm/initial-push`.

This dataset regroup large field-of-view (FOV) T1w and T2w MRI data for 62 subjects. This data was acquired during the PAM50 project in two different centers: AMU (Aix-Marseille Université) and UNF (Unité de neuroimagerie fonctionnelle).

## BIDSification warnings

- Due to inconsistent folders, some images went missing for 4 subjects leading to a warning:

     - T2w contrast:
	   - sub-amuCR
	   - sub-amuTT
	   - sub-unfErssm011
	  
    - T1w contrast:
	   - sub-unfErssm021

- A warning is also raised due to inconsistent scanning parameters between subjects (this warning is normal and due to the different centers used to create this data)

## Related issues

https://github.com/neuropoly/data-management/issues/235 : Treating about the origin of the data and some issues regarding the data.
https://github.com/neuropoly/data-management/issues/240 : Treating about potential image duplicates with the dataset `sct-testing-large`

**Comment by NathanMolinier** [comment]
New corrected discs labels with discs 1 and 2 were added

**Comment by mguaypaq** [comment]
Ok, here's what I did so far:
- Some of the image files were not git-annexed, so I rewrote the branch history to fix the problem.
- I merged the changes so far into `master`.
- I added a `.bids-validator-config.json` file to silence the inconsistent scanning parameters, and the specific missing images listed in the `README.md`.

But before closing this, we should fix some problems with the `dataset_description.json` file:
- The `Authors` field has a weird encoding of Sandrine Bédard's name.
- I'm not sure about using `"DatasetType": "derivative"`, maybe it should be `"raw"`. Or if it's a `"derivative"`, then it also needs a `"GeneratedBy"` field.
- The `"SourceDatasets"` field refers to an empty `sourcedata` directory.

**Comment by NathanMolinier** [comment]
Regarding the `dataset_description.json` file:
- This type of encoding is similar in other dataset (see spine generic) but I changed to use directly the letter with accent
- `"DatasetType": "derivative"` is based on what I found in `dcm-zurich` but I removed it.
- Regarding the `sourcedata` point, I don't know what to do. Should I add the dicom files is the folder ? Should I remove this line in the json and the folder ?

**Comment by mguaypaq** [comment]
Thanks for the fixes.

I added a commit to remove the (essentially empty) `sourcedata/` folder and any references to it in `dataset_description.json`, since this is a raw dataset (meaning that, it was created from non-BIDS sources).

 I merged into `master`, and deleted the `nm/initial-push` branch.
