### ISSUE TITLE
New dataset - `dcm-oklahoma`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#246]
In `jv/add_initial_data` branch, I added initial data for `dcm-oklahoma` dataset.

@mguaypaq, could you please review the branch?

**Comment by mguaypaq** [comment]
It looks like the data was not annexed, so I fixed that. Now, `git clone` is a small download again, `git annex get` works, and `bids-validator .` only has a few warnings, so I merged into `master`:
- `INCONSISTENT_SUBJECTS` for `sub-CSM099_flip-1_mt-on_MTS.nii.gz`, as noted in the `README.md` already.
- `INCONSISTENT_PARAMETERS` and `NO_AUTHORS`, as usual.

**Comment by valosekj** [comment]
Thank you!
