### ISSUE TITLE
New dataset - `sci-paris`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#247]
In `jv/add_initial_data` branch, I added initial data for `sci-paris` dataset. The dataset is based on `~/duke/mri/paris/data_sci/space` data.

@mguaypaq, could you please review the branch?

**Comment by mguaypaq** [comment]
I'll note that `git annex get` is happy, but `bids-validator .` complains that:
```
The compulsory file /dataset_description.json is missing.
```

Merged into master.

**Comment by valosekj** [comment]
> I'll note that `git annex get` is happy, but `bids-validator .` complains that:
> 
> ```
> The compulsory file /dataset_description.json is missing.
> ```

Good catch!

I added the `dataset_description.json` file in `jv/add_dataset_description.json` branch.

**Comment by mguaypaq** [comment]
Ok, I fixed the `BIDSVersion` and added a minimal `.bids-validator-config.json` to ignore `INCONSISTENT_PARAMETERS` and `NO_AUTHORS`.
