### ISSUE TITLE
Add SC seg to `sci-paris`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#249]
I added QCed and manually corrected SC seg for all 14 `sci-paris` subjects in `jv/add_sc_seg` branch.

I also corrected the SCI lesion for `sub-057` within the same branch.

**Comment by naga-karthik** [comment]
I was wondering if this has been merged yet? If not, could you please merge it soon @mguaypaq ? Thank you!

**Comment by mguaypaq** [comment]
Git-annex and bids-validator are happy, so I merged into master and deleted the branch.
