### ISSUE TITLE
Add missing lesion for `sub-mon119_ses-M0_PSIR.nii.gz`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#250]
I added a missing lesion mask for `sub-mon119_ses-M0_PSIR.nii.gz` in `jv/add_missing_lesion_for_sub-edm143_ses-M0` branch.

Context: https://github.com/ivadomed/canproco/issues/34

**Comment by mguaypaq** [comment]
Merged into master, branch deleted.
