### ISSUE TITLE
Corrected discs labels `sct-testing-large`

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#251]
## Description

New manually corrected data for `sct-testing-large` was added regarding discs labelling. These corrections are now available in the branch `nm/correct_dataset`.

## Solved issue

An [issue](https://github.com/neuropoly/data-management/issues/244) regarding non BIDS compliant subject folders was also addressed in this branch.

**Comment by mguaypaq** [comment]
Congratulations on such a large addition!

For the git-annex aspect, everything looks fine.

For bids-validator, there are lots of errors and warnings, but they're not related to this change. So, I merged into master and deleted the branch.

**Comment by NathanMolinier** [comment]
Some images might actually be corrected.

Indeed, I was trying to load some of the new labels but I got an error when using nibabel:
```bash
File "~/code/spinalcordtoolbox/spinalcordtoolbox/image.py", line 429, in loadFromPath
    im_file = nib.load(self.absolutepath, mmap=mmap)
  File "~/.conda/envs/sct_hg_env/lib/python3.8/site-packages/nibabel/loadsave.py", line 115, in load
    raise ImageFileError(msg)
nibabel.filebasedimages.ImageFileError: File ~/data/datasets/sct-testing-large/derivatives/labels/sub-spineGeneric007/anat/sub-spineGeneric007_T2w_labels-disc-manual.nii.gz is not a gzip file
```

The same problem is happening when using fsleyes
<img width="703" alt="Screenshot 2023-08-16 at 3 07 35 PM" src="https://github.com/neuropoly/data-management/assets/68945192/3a970b4f-19f0-43e6-b9e4-a129ff151c2e">
