### ISSUE TITLE
`canproco` - add orientation-corrected-data

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#252]
Originally posted by @plbenveniste in https://github.com/ivadomed/canproco/issues/33:

> When training an nnU-Net, I saw that the model was sensitive to difference in orientation between the image and the mask. With @valosekj we corrected the orientations of these images. 
I have pushed these corrections under the branch `plb/orientation-correction`. 
Who is in charge of verifications and pull requests for the git annex of canoproco ? (@jcohenadad )
>
> Related to #29

**Comment by valosekj** [comment]
I reviewed a few randomly selected subjects. They look good -- image and lesion perfectly overlay each other, and there is no warning when opening them in FSLeyes.

I believe it is safe to merge the branch. @mguaypaq, could you please do it?

**Comment by mguaypaq** [comment]
Thanks for including the processing script. Everything looks fine for git-annex and bids-validator, so I rebased and merged into `master`, then deleted the branch `plb/orientation-correction`.
