### ISSUE TITLE
`canproco` - add `ses-M12` data

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#253]
Originally posted by @jcohenadad and @plbenveniste in https://github.com/ivadomed/canproco/issues/30:

Julien's comment:
> I have received the data. I have copied them under `duke:temp/jcohen/canproco_data_timepointtwo` we need to:

- [x] Make sure they pass BIDS validator
- [x] Add them to git-annex
- [x] Remove temp folder

Pierre-Louis's comment:
> Images pushed to git-annex under branch `plb/insert_time_point`. 
Added code to add new data time point in `canproco/code/insert_time_point_data.py`. 
The previous code generates a report of the data added ; here it is for the M12 data points : 
[insertion_report.txt](https://github.com/ivadomed/canproco/files/11958493/insertion_report.txt)
>
> In summary : 342 new data point added (339 existing sub-ID and 3 new subjects).

**Comment by valosekj** [comment]
I checked the branch.

NIfTI images look good!

I have just one point about `participants.tsv`.  Currently, we already have `participants.tsv` for our git-annex dataset. However, the `M12` data also contains its own `participants.tsv` with the following columns:

```
participant_id sex   age   date_of_scan  institution_id institution   manufacturer  manufacturers_model_name    receive_coil_name    software_versions    researcher
```

We should definitely keep `date_of_scan`, which corresponds to the date of the M12 scan. `age` is also potentially relevant because it corresponds to the age at the M12 scan (so it is different from the age at M0). But honestly, we could maybe also keep all other columns (except `sex`) to keep track of the scanner version etc.

**Comment by jcohenadad** [comment]
> But honestly, we could maybe also keep all other columns (except sex) to keep track of the scanner version etc.

agreed

**Comment by plbenveniste** [comment]
While coding the Python script, I noticed that the`participants.tsv` file from the M12 time point had an error on the column name. 
The M0 dataset's first column is: `participant_id`
While the M12 dataset's first column is: `participant_id ` (beware of the space at the end). 

I made sure in the code that this issue isn't a problem: I changed the new time point file's first column's name to the name of the first column of the M0 file.

**Comment by plbenveniste** [comment]
I modified the `participants.tsv` file in branch `plb/insert_time_point` and merged the data from time point M12. 
I added a script `code/add_new_time_point_participants_tsv.py` to add new time points. 

The column names of the updated participants.tsv file are:
> 	participant_id	sex	age_M0	pathology_M0	phenotype_M0	date_of_scan_M0	institution_id_M0	institution_M0	manufacturer_M0	manufacturers_model_name_M0	receive_coil_name_M0	software_versions_M0	edss_M0	age_M12	date_of_scan_M12	institution_id_M12	institution_M12	manufacturer_M12	manufacturers_model_name_M12	receive_coil_name_M12	software_versions_M12	researcher_M12

In the case of the 3 new subjects at M12, they have None values for all columns from M0. I also included a feature in the code to add the sex of newly added subjects to the dataset.

@valosekj  Everything is ready for verification.

**Comment by valosekj** [comment]
Thanks for the update, @plbenveniste!

> The M0 dataset's first column is: participant_id
> While the M12 dataset's first column is: participant_id  (beware of the space at the end).
> I made sure in the code that this issue isn't a problem

Good catch! 

The updated `participants.tsv` now looks good! Only three minor comments:
1. Please, use `'n/a'` for missing values instead of space. You can use, for example:

```python
participants_df.to_csv(args.participants_file, sep='\t', na_rep='n/a', index=False)
```

2. It is probably not necessary to keep the column `researcher_M12`, which is `n/a` for all subjects. I would remove this column.

3. Please, also update `participants.json` with the new columns.

**Comment by plbenveniste** [comment]
Correction done. 
I adapted the code to modify the .tsv and .json files. 
Because the .json file from the new time point didn't have all the information describing the columns, I used the code to modify the `participants.tsv` file and then manually added the information. 
Commit pushed to `plb/insert_time_point`branch.

**Comment by valosekj** [comment]
Great, thanks! LGTM now!

@mguaypaq, could you please also check the `plb/insert_time_point` branch and merge it if you find it ok?

**Comment by mguaypaq** [comment]
Everything looks good from the point of view of `git annex get`, so I rebased and merged into `master`, and deleted the `plb/insert_time_point` branch.

**Comment by plbenveniste** [comment]
Temp folder (`duke/temp/jcohen/canproco_data_timepointtwo`) removed from duke
