### ISSUE TITLE
New dataset - `twh-rootlets`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#257]
In the `jv/add_data` branch, I added initial data for the `twh-rootlets` dataset. 
The dataset is a BIDSifided version of data available on `duke/mri/twh/2015-cadotte`. Since no JSON sidecars were available on duke, I did not include any JSON sidecars in the BIDSifided dataset.

Thanks to @tzebre for helping to prepare the dataset. 

@mguaypaq, could you please review the branch?

**Comment by jcohenadad** [comment]
I just realized: are we sure that these data are not already in git-annex? eg under `sct-testing-large`

**Comment by valosekj** [comment]
> I just realized: are we sure that these data are not already in git-annex? eg under `sct-testing-large`

To verify this, I tried the following searches on `sct-testing-large/participants.tsv`:
- `grep "twh" participants.tsv` - this returns `sub-twh` DCM and HC subjects from Allan
- `grep "root" participants.tsv` - no match
- `grep "nerve" participants.tsv` - no match
- `grep "cadotte" participants.tsv` - this returns a single subject `sub-calCadotte001` from 2017 (the `twh-rootlets` dataset is from 2015)

I also checked other git-annex datasets (`ssh git@data.neuro.polymtl.ca info`), and there is no relevant one.

--> I believe that these data are not  already in git-annex.

**Comment by mguaypaq** [comment]
Both `git annex get` and `bids-validator .` are happy, so: merged into master.
