### ISSUE TITLE
New dataset `data_axondeepseg_unmyelinated`

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/data-management#263]
The initial data commit is in `ac/init`.
The bids-validator will complain about INCONSISTENT_SUBJECTS but that's expected.

**Comment by mguaypaq** [comment]
Both `git annex get .` and `bids-validator .` are happy, so I merged into `master` and deleted the branch `ac/init`. I also added an extra commit to make bids-validator ignore the INCONSISTENT_SUBJECTS warning.
