### ISSUE TITLE
Improving MS lesion ground segmentation 

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#267]
Improvement from @Nilser3 (rater2): https://amubox.univ-amu.fr/s/7gF5EqynwG3CkT6

Feedback from @jcohenadad (only reviewed MRS00 --> MRS11): [feedback_seg_nilser.zip](https://github.com/neuropoly/data-management/files/12786631/feedback_seg_nilser.zip)

Overall, I find the segmentations too "spotty". See [guidelines for Basel](https://github.com/ivadomed/model_seg_ms_mp2rage/issues/56), and notably [this comment](https://github.com/ivadomed/model_seg_ms_mp2rage/issues/56#issuecomment-1374862637).

**Comment by Nilser3** [comment]
Hi @jcohenadad 

I have followed your feedback and the guidelines, 
[Here is the QC](https://github.com/neuropoly/data-management/files/12876061/qc_lesions_marseille-3T-mp2rage_II.zip) for the subjects MRS00 to MRS11

**Comment by jcohenadad** [comment]
This is much better Nilser! 

Minor comments:

**sub-MRS09_ses-M0_UNIT1.nii.gz**
- I would remove the segmentation above C1:
![image](https://github.com/neuropoly/data-management/assets/2482071/6944090c-6b55-4b19-be25-430340b56317)

**sub-MRS09_ses-M24_UNIT1.nii.gz**
- I would remove the segmentation above C1
- I find the lesions slightly under-segmented
![image](https://github.com/neuropoly/data-management/assets/2482071/635ef7f0-e3d6-4e4b-87c0-271033271b83)

**Comment by Nilser3** [comment]
Following the previous comments,
[here](https://github.com/neuropoly/data-management/files/13361072/ms_marseille-3T-mp2rage.zip) the improved MS lesion GT for `marseille-3T-mp2rage`

**Comment by jcohenadad** [comment]
It looks good @Nilser3 , good job 👏
These modified GTs can be added to the database. What is the strategy here: to replace rater1 or to add rater2? 
And if we add rater2, how can we be sure that in the future, we will use the correct GTs for training models?

**Comment by Nilser3** [comment]
Thanks you @jcohenadad ,
I think it would be good to add the `rater2` masks to the database and explain on the `intranet` that it is necessary to read the `.json` files to see the difference between masks. 

Actually:

`cat sub-MRS00_ses-M0_UNIT1_label-lesion_rater1.json`
```
{
  "Author": "Sarah Demortière",
  "Date": "2019-01-01"
}
```

`cat sub-MRS00_ses-M0_UNIT1_label-lesion_rater2.json`
```
{
  "Author": "Sarah Demortière",
  "Date": "2019-01-01"
}

{
  "Author": "Nilser Laines Medina",
  "Date": "2023-09-01"
  "Note": "After consensus on the number and location of lesions"
}
```

**Comment by Nilser3** [comment]
MS ground truth improvements on:

branch: `nlm/ms_lesion_improvement`
commit `2b628b8c86fb956937da90be17615643c6d49d8b`

ready for PR

**Comment by Nilser3** [comment]
Hello @mguaypaq 
Could you please check my PR?

thanks

**Comment by mguaypaq** [comment]
This is only changing the `*_label-lesion_rater2.nii.gz` image files, but not the associated JSON sidecars, is this normal? Shouldn't there be a new step listed in the JSON, or at least a more recent date? Presumably these improved files are from after 2023-09-01.

Also, I'll note that the JSON sidecars are not properly formatted, because they contain 2 top-level json objects, instead of a single one, and there's a missing comma. I know we're still discussing the exact details in #282, but at least this would be a reasonable syntax:
```json
{
  "GeneratedBy": [
    {
      "Author": "Sarah Demortière",
      "Date": "2019-01-01"
    },
    {
      "Author": "Nilser Laines Medina",
      "Date": "2023-09-01",
      "Note": "After consensus on the number and location of lesions"
    }
  ]
}
```

**Comment by Nilser3** [comment]
Thanks for the comments @mguaypaq  
you are right, I updated the date and I have changed the associated  JSON sidecars for  `*_label-lesion_rater2.nii.gz` files.

`branch`: nlm/ms_lesion_improvement
`commit`: 2a5d27389d65853924bafcd1f7ccc0f5d73ee9b5

ready for PR

**Comment by mguaypaq** [comment]
Happy new year!

I looked at your most recent commit, and the JSON files look good now, thanks. But I'd like to check: your commit message says `add non-den images`, but the actual commit only touches the JSON files, is this normal? Did you also want to update the images themselves?

Also, I think the `_rater1`/`_rater2` suffix is not really BIDS, maybe it could go in a `_desc-rater1_` entity instead, but that's a separate issue, and it can be a separate pull request.

**Comment by Nilser3** [comment]
Thank you @mguaypaq  , happy new year to you too  👍 

> I looked at your most recent commit, and the JSON files look good now, thanks. But I'd like to check: your commit message says `add non-den images`, but the actual commit only touches the JSON files, is this normal? Did you also want to update the images themselves?
> 
my bad, I didn't write a good message 

> Also, I think the `_rater1`/`_rater2` suffix is not really BIDS, maybe it could go in a `_desc-rater1_` entity instead, but that's a separate issue, and it can be a separate pull request.

Indeed, I have renamed all the `rater1`/`rater2 ` files (bids-validator seems to be happy)


### Latest modifications : 

`branch:` nlm/ms_lesion_improvement
`commit:` eb639675a5a5ae2bcd722e8f03d8c85e3cd24d88 

ready for PR

**Comment by mguaypaq** [comment]
Ok, I reworded the commit message (so the commit is now 3b3ebce55565a775fb1d5946f0a16e3027528324), and merged into master. Thanks!

**Comment by jcohenadad** [comment]
Reopening, because it would be important to clarify in the README what those manual segmentations represent. Otherwise, a student in the future will consider rater1 and rater2 as two _independent_ annotations, which would be wrong.

suggestion:
~~~
## derivatives

- sub-MRSXX_ses-MYY_UNIT1_label-SC_seg
- sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater1: done by XXX
- sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater2: done by XXX, and corrected by Nilser under the supervision of Julien. We recommend to ONLY use these annotations.
~~~

**Comment by Nilser3** [comment]
done @jcohenadad 
branch: nlm/update_readme
commit: 4940740eedb977b866ef26fa88e276584a50de27

ready for PR @mguaypaq

**Comment by mguaypaq** [comment]
The change looks good, merged into `master`:

```diff
commit 4940740eedb977b866ef26fa88e276584a50de27 (HEAD -> master, origin/master, origin/HEAD)
Author: Nilser Laines Medina <nilaia@rosenberg.neuro.polymtl.ca>
Date:   Tue Jan 23 09:42:42 2024 -0500

    Update README file, adding description of the raters and manual segmentations

diff --git a/README.md b/README.md
index 90f63ff..ee6a4e8 100644
--- a/README.md
+++ b/README.md
@@ -27,6 +27,12 @@ sub-MRSXX_ses-MYY_UNIT1
 - sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater1
 - sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater2
 
+## derivatives
+
+- sub-MRSXX_ses-MYY_UNIT1_label-SC_seg : done by Samira Mchinda, from SC masks generated by sct_deepseg_sc, SCT Version 5.3.0
+- sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater1: done by Sarah Demortière
+- sub-MRSXX_ses-MYY_UNIT1_label-lesion_rater2: done by Sarah Demortière, and corrected by Nilser under the supervision of Julien (see https://github.com/neuropoly/data-management/issues/267). We recommend to ONLY use these annotations.
+
 ## Authors: 
 
 - Virginie Callot,
```
