### ISSUE TITLE
New dataset `data_axondeepseg_stanford`

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/data-management#272]
Hi. Would it be possible to create a new dataset called `data_axondeepseg_stanford` and grant me write access? 
Additionnally, we might want to rename the `data_axondeepseg_unmyelinated` dataset to disambiguate with this new one. Should I create a separate issue for this?

**Comment by mguaypaq** [comment]
I can deal with both on this issue, no problem. What would you like the two repo names to be?

**Comment by hermancollin** [comment]
- `data_axondeepseg_stanford` for this one
- `data_axondeepseg_unmyelinated` -> `data_axondeepseg_sickkids`

**Comment by mguaypaq** [comment]
Done, and done. Sorry for the delay.
