### ISSUE TITLE
Canproco - adding spinal cord segmentation files on PSIR and STIR contrasts

### ISSUE THREAD

**Issue by plbenveniste** [neuropoly/data-management#273]
Opening this issue for branch : `jv/add_manually_corrected_sc_PSIR_STIR_seg`. 

In this branch, we added the spinal cord segmentation and the associated json files of the patients for contrasts PSIR and STIR, except for those in the [excluce.yml](https://github.com/ivadomed/canproco/blob/main/exclude.yml) file.

These sc seg where QCed (see [here](https://github.com/ivadomed/canproco/issues/46#issuecomment-1768512894)) and some of them were manually corrected. 

Thank you for reviewing this :) 

Note that we are aware of our [`label-SC_seg.nii.gz` convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#derivatives-structure) for SC seg, but to be consistent with already existing `T2w_seg-manual.nii.gz` files, we used `STIR_seg-manual.nii.gz`/`PSIR_seg-manual.nii.gz`.

**Comment by mguaypaq** [comment]
Rebased and merged into `master`, and deleted the branch `jv/add_manually_corrected_sc_PSIR_STIR_seg`.
