### ISSUE TITLE
New dataset `dcm-zurich-lesions-20231115`

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#281]
@mguaypaq, could you please initialize `dcm-zurich-lesions-20231115` and grant me and @naga-karthik write permissions? Thanks!

**Comment by mguaypaq** [comment]
Ok, I initialized the repository and gave you both write access @valosekj @naga-karthik. I used my new repository template based on [the intranet instructions](https://intranet.neuro.polymtl.ca/data/dataset-curation.html) including some example files, let me know what you think.

**Comment by valosekj** [comment]
> Ok, I initialized the repository and gave you both write access @valosekj @naga-karthik. 

Thanks! I added the initial data and updated BIDS files (participants files, README) in the `jv/add_initial_data` branch.
Can you please check it and merge?

> I used my new repository template based on [the intranet instructions](https://intranet.neuro.polymtl.ca/data/dataset-curation.html) including some example files, let me know what you think.

Looks good!

**Comment by mguaypaq** [comment]
I see that you included a `dataset_description.json` file for the derivative as well, nice! But, [the standard says](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#derived-dataset-and-pipeline-description) that for derivatives this must include a `GeneratedBy` key. So I added the following:
```json
    "GeneratedBy": [
        {
            "Name": "Manual",
            "Description": ""
        }
    ]
```

For `participants.{json,tsv}`, I wonder:
* Is it relevant including the `age` and `sex` columns if all the values are `n/a`?
* Is it relevant to include the `pathology` and `institution` columns if all the values are constant? The single value could just be mentioned in the `README.md`. But I guess this makes it easier to write scripts which analyze all of our datasets, like @NathanMolinier is doing.
* Speaking of which, [the list of recommended fields on the intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#participants-tsv) also says `species` should always be included, why not here?

For git-annex, everything is fine.

For bids-validator, it looks 7 of the images are bigger than the others, is this expected? If so, I can configure bids-validator to ignore this warning.
```
	1: [WARN] Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
		./sub-01/anat/sub-01_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
		./sub-02/anat/sub-02_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
		./sub-03/anat/sub-03_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
		./sub-04/anat/sub-04_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
		./sub-05/anat/sub-05_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
		./sub-06/anat/sub-06_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,23 (voxels).
		./sub-38/anat/sub-38_acq-ax_T2w.nii.gz
			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,22 (voxels).
```

**Comment by valosekj** [comment]
> I see that you included a `dataset_description.json` file for the derivative as well, nice! But, [the standard says](https://bids-specification.readthedocs.io/en/stable/modality-agnostic-files.html#derived-dataset-and-pipeline-description) that for derivatives this must include a `GeneratedBy` key. So I added the following:
> 
> ```json
>     "GeneratedBy": [
>         {
>             "Name": "Manual",
>             "Description": ""
>         }
>     ]
> ```

Okay! Thanks for this! I filled the `Description` entry in my latest commit.
I also [updated](https://github.com/neuropoly/intranet.neuro.polymtl.ca/commit/8983e307b7c43fc8a53e7ef2e8c4c987af127d10) our intranet.



> For `participants.{json,tsv}`, I wonder:
> 
> * Is it relevant including the `age` and `sex` columns if all the values are `n/a`?

Yeah, this might be probably deleted.

> * Is it relevant to include the `pathology` and `institution` columns if all the values are constant? The single value could just be mentioned in the `README.md`. But I guess this makes it easier to write scripts which analyze all of our datasets, like @NathanMolinier is doing.

I would keep the `pathology` and `institution` columns even though the values are constant. Someone can open just `participants.tsv`, so it is better to have this information also here.

> * Speaking of which, [the list of recommended fields on the intranet](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#participants-tsv) also says `species` should always be included, why not here?

Good point! I was actually thinking if to keep or deleting this column. I decided to remove it, but you are right. To be consistent we should include it.

> For git-annex, everything is fine.
> 
> For bids-validator, it looks 7 of the images are bigger than the others, is this expected? If so, I can configure bids-validator to ignore this warning.
> 
> ```
> 	1: [WARN] Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
> 		./sub-01/anat/sub-01_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
> 		./sub-02/anat/sub-02_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
> 		./sub-03/anat/sub-03_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
> 		./sub-04/anat/sub-04_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
> 		./sub-05/anat/sub-05_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,24 (voxels).
> 		./sub-06/anat/sub-06_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,23 (voxels).
> 		./sub-38/anat/sub-38_acq-ax_T2w.nii.gz
> 			 The most common set of dimensions is: 320,320,15 (voxels), This file has the dimensions: 320,320,22 (voxels).
> ```

Yes, some images have more slices than others. It is fine.

**Comment by mguaypaq** [comment]
Ok, I removed the `age` and `sex` columns, and added `species` as `homo sapiens`. Then I merged into `master` and deleted `jv/add_initial_data`.

**Comment by valosekj** [comment]
> Ok, I removed the `age` and `sex` columns, and added `species` as `homo sapiens`. Then I merged into `master` and deleted `jv/add_initial_data`.

Thanks!
