### ISSUE TITLE
Strategy to synthesize UNIT1 contrast from T1map images

### ISSUE THREAD

**Issue by Nilser3** [neuropoly/data-management#283]
# Description 

The `nih-ms-mp2rage` dataset contains `UNIT1-denoised` data and `T1-maps` (see https://github.com/neuropoly/data-management/issues/280#issuecomment-1817582877 ), however for MS lesion segmentation  `UNIT1 non-denoised` is classically used (and it is the contrast that we have for the other MS MP2RAGE datasets: `marseille-3T-mp2rage` and `basel-mp2rage`), 
so a strategy is required to be able to synthesize `UNIT1 non-denoised`  images from the `T1-maps`.

## UNI-den
![image](https://github.com/neuropoly/data-management/assets/77469192/f8f5720a-235a-4114-a50c-db07e35d578c)

## T1-map
![image](https://github.com/neuropoly/data-management/assets/77469192/5f733778-d7b9-435f-a7f9-5fa0427b7d56)

# Strategy:

- The synthesis of UNI images from T1maps was reported in the work of [Massire et al., 2021](https://pubmed.ncbi.nlm.nih.gov/32852445/) 
- For this synthesis, some MP2RAGE acquisition parameters are required such as : `nbefore, nafter, alpha1, alpha2, TR, MP2RAGE-TR, TI1 and TI2`. Parameters not available for the `nih-ms-mp2rage` data, 
but if I take the parameters reported by [Demortière et al., 2020](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7342757/) 
I obtain the following results:

## Synthetic UNI from non-den T1-map
![image](https://github.com/neuropoly/data-management/assets/77469192/c4fc54c9-c0fb-4ad4-93ea-7470e62e3de8)

I believe that we would have more precise results if we have the MP2RAGE parameters from `nih-ms-mp2rage` data. 

## Related issues: 
#280

**Comment by jcohenadad** [comment]
I'm not a fan of this two-step strategy-- what if the synthesis misses minor lesions? Why not train a model with den-UNI1 and non-denUNI1 first and see what you get?
