### ISSUE TITLE
Correct discs labels for the dataset sct-testing-large

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#294]
## Description

I just pushed a branch called `nm/correct-discs` in the `sct-testing-large` dataset to add missing intervertebral discs and correct few mistakes.

The branch can now be merged.

**Comment by mguaypaq** [comment]
The json sidecars look fine, and all the image files are properly git-annexed. There's a bunch of errors returned by bids-validator, but it looks like they're all pre-existing errors. Merged into master.
