### ISSUE TITLE
Updating CanProCo M0 data with Erin's new data

### ISSUE THREAD

**Issue by plbenveniste** [neuropoly/data-management#296]
I am creating this issue to detail the work which has been done on the CanProCo data on branch : `plb/add_erin_corrected_data_at_M0`. This comes from the fact that some M12 images were confused with M0 images when sent to us. We realized that when we saw that some M0 and M12 images were identical : 

- Update CanProCo data with Erin's verified data
- Move segmentation from M0 to M12 when appropriate (we verified if the segmentations matched the images at M12)
   - lesion segmentations for PSIR and STIR
   - spinal cord segmentation for T2w 
- Manually segment M0 subjects which didn't have any segmentation

More details can be found in this [issue 39](https://github.com/ivadomed/canproco/issues/39) ! 

Tagging @mguaypaq for verification and merging.

**Comment by mguaypaq** [comment]
This is a big change! Congratulations on getting it done (and all the investigations before).

Git-annex seems fine (including for all the intermediate commits on the branch).

Bids-validator complains about MISSING_SESSION for lots of subjects, but I guess that's expected; not everyone has both M0 and M12. (I'm a bit surprised to see some subjects with M12 but **no** M0, though, is that normal?) I can add a `.bids-validator-config.json` to ignore this error, if it's normal.

Bids-validator also complains about INCONSISTENT_SUBJECTS (that is, missing T2w images) for `sub-cal104` and `sub-cal128`. Looking at `README.md` and `.bidsignore`, I only see some other subjects mentioned with missing data:
* In `README.md`:

  ```
  # t2w
  - sub-cal088_ses-M0   # Poor data quality
  - sub-cal209_ses-M0   # Missing T2w file
  # MT
  - sub-cal161          # Missing MT data
  ```
* In `.bidsignore`:

  ```
  # Poor data quality
  sub-cal088/ses-M0

  # Missing T2w file
  sub-cal209/ses-M0
  ```

Can you add `sub-cal104` and `sub-cal128` to `README.md` and `.bidsignore`?

**Comment by plbenveniste** [comment]
Thanks for checking everything @mguaypaq . 

We didn't have any instructions whether a subject should always be included at M0. Therefore, having subjects at M12 but not M0 isn't a problem. 

`sub-cal104` and `sub-cal128` were both added to `README.md` and `.bidsignore`. 

However, before merging, I realized that there was still an issue with the splitting of MT files for M12 subjects. Working on this now, using the code `split_4D_MT.sh` from branch `jv/update_split_4D_MT_script`.

**Comment by plbenveniste** [comment]
MT files were split using the code from `jv/update_split_4D_MT_script`. (The script has not been changed in branch `plb/add_erin_corrected_data_at_M0` to avoid conflict with other branch. However, maybe it would make sense to merge both branch before pushing. 

All good on my side !

Thanks for your review 😀

**Comment by mguaypaq** [comment]
Merged into master, with an extra commit to ignore MISSING_SESSION in bids-validator.
