### ISSUE TITLE
`data_axondeepseg_stanford` update with labels

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/data-management#297]
Hello. I just uploaded new annotations in `data_axondeepseg_stanford`. Would it be possible to merge the changes? They are located in the `ac/add_labels_corrected` branch - please disregard `ac/add_labels` in which I made a mistake (can be safely deleted).
Thanks

**Comment by hermancollin** [comment]
Actually - don't know if @mguaypaq you have started working on this, but we should put this merge on hold. I expect the stanford group to send more data in the following week. It might be simpler to add this to the current PR.

**Comment by hermancollin** [comment]
Hey @mguaypaq. I updated the dataset and pushed my commits to the `ac/add_labels_corrected` branch. I haven't had the chance to connect via cable to neurogitea so I can't use it ATM for a PR :cry:

**Comment by hermancollin** [comment]
Hey @mguaypaq I received and curated a lot of new masks for this dataset. I created a PR on neurogitea:  https://data.neuro.polymtl.ca/datasets/data_axondeepseg_stanford/pulls/1

**Comment by mguaypaq** [comment]
The neurogitea PR got merged :tada:
