### ISSUE TITLE
New dataset: `data_axondeepseg_cars`

### ISSUE THREAD

**Issue by hermancollin** [neuropoly/data-management#298]
Hi. Last week I finished annotations for this new dataset (CARS modality). Would it be possible to create a new dataset called `data_axondeepseg_cars` and give me W access?

It's already formatted in BIDS format and passes the bids-validator. Images and labels are in PNG format.

**Comment by mguaypaq** [comment]
Done, I created `data_axondeepseg_cars`, put `.gitignore` and `.gitattributes` in there, and gave you W access. You should be able to clone it, create a branch, add your files, and push your changes.
