### ISSUE TITLE
Canproco SC segmentation were saved with a wrong header

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#305]
## Description

I tried to work with T2w spinal cord (SC) segmentations stored in the `canproco` dataset and I noticed that images from `Calgary` were saved with a wrong header. Leading to a wrong display and more troubles.
<img src=https://github.com/neuropoly/data-management/assets/68945192/e6a6de23-0b50-4c35-bdde-bb372b30423e alt="drawing" width="500"/>

In the RPI system:
| Header | Image | SC segmentation |
|:---:|:---:|:---:|
|X (pixel)|56|56|
|Y (pixel)|512|320|
|Z (pixel)|512|320|
|px (mm/pixel)|0.800011|0.800011|
|py (mm/pixel)|0.5|0.5|
|pz (mm/pixel)|0.5|0.5|

The real resolution for the SC segmentation should be:
- px = 0.800011 mm/pixel
- py = 0.8 mm/pixel
- pz = 0.8 mm/pixel

## Solution

To fix this I wrote a [script](https://github.com/NathanMolinier/vrac/blob/main/fix_canproco_calgary.py) to overwrite the header. Also, I would like to save the SC segmentations in the same space as the one used for images to simplify future use.

## Related issues

- https://github.com/neuropoly/data-management/issues/197
- https://github.com/neuropoly/data-management/issues/303

## Note provided in the README

Note: T2w sagittal images were preprocessed before the spinal cord was segmented ('_T2w_seg-manual.nii.gz') and disc labels were identified ('_T2w_labels-manual.nii.gz').
Namely, reorientation to RPI and resampling to 0.8mm isotropic voxel were performed. This is why the original T2w images have different dimensions than segmentations and labels.
Preprocessing steps: https://github.com/ivadomed/canproco/blob/8e1b2c35f96eeeb3838b512dd93eba25e5a5e97a/scripts-t2w_csa/sct-preprocess_data.sh#L162-L170
For context, see https://github.com/neuropoly/data-management/issues/197
> I tried the preprocessing steps but it did not work

**Comment by valosekj** [comment]
Good catch @NathanMolinier! Thanks for reporting this! I wonder how that could happen! 

Can you please list the problematic subejcts?
I looked at the first one (`sub-cal056`) and dimensions are fine:

```console
# Raw T2w image: 0.8, 0.5, 0.5
canproco$ sct_image -i sub-cal056/ses-M0/anat/sub-cal056_ses-M0_T2w.nii.gz -header | grep pixdim
pixdim		[1.0, 0.8, 0.5, 0.5, 2.51667, 0.0, 0.0, 0.0]

# SC seg obtained from resampled and reoriented image: 0.800011, 0.8, 0.8
canproco$ sct_image -i derivatives/labels/sub-cal056/ses-M0/anat/sub-cal056_ses-M0_T2w_seg-manual.nii.gz -header | grep pixdim
pixdim		[-1.0, 0.800011, 0.8, 0.8, 1.0, 1.0, 1.0, 1.0]
```

**Comment by NathanMolinier** [comment]
I double checked the subject `sub-cal056` with a fresh git-annex download and these are the images that I get.
<img src=https://github.com/neuropoly/data-management/assets/68945192/e6a6de23-0b50-4c35-bdde-bb372b30423e alt="drawing" width="300"/>

So it looks like you are using a modified (or older) version of the `canproco` dataset. Because the problem that I showed is the same for every subject from calgary (`sub-calXXX`).

To avoid future mistakes I think it would be preferable to push my modified images to git-annex. Also, to simplify the future use of the data, I added these [lines](https://github.com/NathanMolinier/vrac/blob/f40f8cf071664580324c89e54ed948e6424a1448/fix_canproco_calgary.py#L57-L69) to my script to put the SC segmentations in the same space as the one used for images. Is it ok ?

**Comment by NathanMolinier** [comment]
After more investigation I found this commit:
![Screenshot 2024-03-26 at 10 14 31](https://github.com/neuropoly/data-management/assets/68945192/a5b0e9c2-d909-483f-b7c1-a5a4a8613f26)

I checked out to the previous commit and downloaded the same images from `sub-cal056`:
<img width="300" alt="Screenshot 2024-03-26 at 10 33 55" src="https://github.com/neuropoly/data-management/assets/68945192/7e375170-061a-4595-8355-e909e067f3d6">

This commit is indeed the problem.

Did something unexpected could have happened @plbenveniste ?

**Comment by plbenveniste** [comment]
Thanks for highlighting this ! Great catch ! 
This is the script used : [dataset_correction.py](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py). 
I wonder what could have happened. Maybe, we should take a look at the other datasets as well then ...

**Comment by jcohenadad** [comment]
> This is the script used : [dataset_correction.py](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py).

It would be useful to see the terminal log (ie stdout) of the script applied to the dataset, so we can investigate what differed _before_ applying the script, and what changed (or was supposed to change).

**Comment by valosekj** [comment]
It seems that the [dataset_correction.py](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py) script iterated not only through PSIR/STIR images (used by Pierre-Louis for his trainings) but also through T2w images due to [line 22](https://github.com/ivadomed/ms-lesion-agnostic/blob/plb/dataset_aggregation/dataset_aggregation/dataset_correction.py#L20-L22). Then since the T2w SC segs had different orientation and resolution than the T2w images (because [reorientation and resampling were applied before SC seg](https://github.com/ivadomed/canproco/blob/8e1b2c35f96eeeb3838b512dd93eba25e5a5e97a/scripts-t2w_csa/sct-preprocess_data.sh#L162-L170)), the script incorrectly copied the T2w header to T2w SC seg ([line 64](https://github.com/ivadomed/ms-lesion-agnostic/blob/cf70c890e6402e61f573fa58a686277ebb1c6c62/dataset_aggregation/dataset_correction.py#L63-L64)).  

I believe, we can recover T2w SC segs by going back in the git history.

BTW. I would also be very careful about other contrasts and datasets since the script could have also modified other images in an unpredictable way.

**Comment by NathanMolinier** [comment]
I fixed the SC segmentation headers, resampled them and reoriented all the images to RPI using this [script](https://github.com/NathanMolinier/vrac/blob/main/fix_canproco_calgary.py). I also QCed the final segmentations to make sure that everything was OK.

Now, I just need to push the data but I have to ask for the access first.

> Notes: I noticed that the subject `sub-cal088` had a really bad SC segmentation probably due to the artifacts present in the image, however I still updated the header. I also noticed that the subject `sub-064` had a T2w image but no SC segmentations even if the image looks good.

**Comment by jcohenadad** [comment]
Few comments:
- this script https://github.com/NathanMolinier/vrac/blob/main/fix_canproco_calgary.py should include at the top a cross-reference to this issue, so in 10 years we know what the purpose of this script is
- also, we should make sure that the output segmentation files are in DTYPE UINT8 to save space

**Comment by plbenveniste** [comment]
Closing this issue as corrections were applied, and corrected data was merged in the main branch. 
Thanks everybody for your feedback!
