### ISSUE TITLE
Different size of T2w images and SC segmentations 

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#306]
Just for the record, T2w SC segmentations are smaller than the original T2w images. Namely, the segmentation has fewer slices (606 vs 691):

![image](https://github.com/neuropoly/data-management/assets/39456460/4550d487-a158-46d7-a383-37dda9614ab6)

<details><summary>example image</summary>

SC seg in red covers fewer slices than the background image:

![image](https://github.com/neuropoly/data-management/assets/39456460/3e225f05-fdf9-470f-b0f1-a5ade04fa12e)

</details>

@NathanMolinier is aware of this and is waiting for the new manually corrected segmentations from Yehuda.

**Comment by NathanMolinier** [comment]
Solved in #308
