### ISSUE TITLE
Fix canproco SC segmentations

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#307]
## Description

I created this issue to mention that I pushed a new branch `nm/fix_calgary_and_resample` on the canproco dataset. This commit is fixing header issues (see https://github.com/neuropoly/data-management/issues/305) with the subjects from Calgary. Also, to limit future mistakes, the SC segmentations were resampled to be in the same space as the images.

## Related issue
https://github.com/neuropoly/data-management/issues/305

**Comment by NathanMolinier** [comment]
We need to update the dtype to uint8 https://github.com/neuropoly/data-management/issues/305#issuecomment-2045889662

**Comment by NathanMolinier** [comment]
I just used this command to convert all SC segmentation from Calgary to dtype uint8:
```bash
for sub in sub-cal*;do for file in $(find -type f -name "$sub"*_seg-manual*.nii.gz);do git annex get "$file"; sct_image -i "$file" -type uint8;done;done
```
The branch `nm/fix_calgary_and_resample` is now ready to merge

**Comment by mguaypaq** [comment]
I turned this into a PR on the canproco dataset and merged it :+1:
