### ISSUE TITLE
Add total segmentator data to whole-spine

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#308]
## Description

I just pushed a new branch `nm/add_totalseg_segmentations` to the whole-spine dataset with `spine` segmentations and new `SC` segmentations.

I also ran this following command to make sure that segmentations are stored as uint8:
```bash
for file in  */*/*label-*.nii.gz;do sct_image -i "$file" -type uint8;done
```

The branch is then ready for review.

I used these codes:
- https://github.com/NathanMolinier/vrac/blob/main/BIDSIFICATION/totalseg_data/remove_SC_and_CSF_seg_from_SPINE_whole-spine.py
- https://github.com/NathanMolinier/vrac/blob/main/BIDSIFICATION/totalseg_data/split_SC_and_spine_seg_whole-spine.py

## Related issue

https://github.com/neuropoly/data-management/issues/306

**Comment by NathanMolinier** [comment]
I still need to change something before merging

**Comment by NathanMolinier** [comment]
I erased SC and CSF segmentation from `label-spine_dseg` and saved them as single files. I also removed single sacrum masks and added them to `label-spine_dseg`.

The branch is now ready for review !

**Comment by mguaypaq** [comment]
Git-annex and bids-validator look fine, merged in https://data.neuro.polymtl.ca/datasets/whole-spine/pulls/1.
