### ISSUE TITLE
Split `label-multi_dseg` and merge sacrum with spine data spider-challenge-2023

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#309]
## Description

I just pushed a branch `nm/add_totalseg_segmentations` to the `spider-challenge-2023` dataset. I used this branch to split the original `_label-multi_dseg` into 2 different labels:
- spine segmentations (including discs and vertebrae segmentation) called `_label-spine_dseg`
- spinal canal segmentations called `_label-canal_seg`

The sacrum segmentation was also added to the spine segmentation and the individual files `_label-sacrum_seg` were removed.

I used this code https://github.com/NathanMolinier/vrac/blob/main/BIDSIFICATION/totalseg_data/add_sacrum_corrections_spider.py

This branch is now ready to be merged.

**Comment by mguaypaq** [comment]
Reviewed and merged in https://data.neuro.polymtl.ca/datasets/spider-challenge-2023/pulls/1.
