### ISSUE TITLE
New dataset `exvivo-spinal-cord`

### ISSUE THREAD

**Issue by Nilser3** [neuropoly/data-management#311]
# Description

Dataset for managing ex-vivo human spinal cord MRI data. Potentially useful for training new GM/WM segmentation models.
The idea is to add more subjects, for the moment 02 subjects to start with.

## Details

`sub-exvivo001`
- from [Calabrese et al., (2018)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5988447)
- Modality: 7T GRE T2star, RD, MD, FA, DWI, B0, AD
- Resolution: ${100 µm^3}$    isotropic    
- Levels: C1-L5
- GT: GM and WM 

`sub-exvivo002`
- from [Henmar et al., (2020)](https://www.biorxiv.org/content/10.1101/2020.07.01.182444v2.full.pdf+html)
- Data available on : [Link](https://erda.ku.dk/public/archives/492d3cc45b7c910829a64d1c196b33e7/published-archive.html#)
- Modality: 9.4T T2w RARE
- Resolution: $50 x 50 x 200 µm ^3 $
- Levels: C3-L5
- GT: GM and WM

**Comment by Nilser3** [comment]
Hi @mguaypaq, 
Could you please create a repository for `exvivo-spinal-cord` dataset
Thank you

**Comment by Nilser3** [comment]
## Potential subject to add: 

Currently on `model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg` dataset there is a subject with `top` and `bottom` acquisitions, with incomplete segmentations (see images). 
This data was used to train [seg_exvivo_gm-wm_t2](https://github.com/ivadomed/model_seg_exvivo_gm-wm_t2_unet2d-multichannel-softseg)

![image](https://github.com/neuropoly/data-management/assets/77469192/57f59b43-44d6-4fa7-ae1c-6e7f2c96282d)

![image](https://github.com/neuropoly/data-management/assets/77469192/3c98a801-31fc-4fca-9a81-47695149ceac)

I propose to centralize this subject on `exvivo-spinal-cord` dataset, with a previous culmination/correction of its GM/WM segmentations.

Comments please @jcohenadad

**Comment by jcohenadad** [comment]
~also tagging @plbenveniste who worked on this~

EDIT Julien Cohen-Adad 2024-05-27: nevermind, I confused with the mouse exvivo dataset

**Comment by mguaypaq** [comment]
Done: I created the new repo here, and added @Nilser3 and @plbenveniste as collaborators (so that they have write access):
https://data.neuro.polymtl.ca/datasets/exvivo-spinal-cord

For actually adding the data, you should open a pull request over there. You can see the instructions on the lab manual:
https://intranet.neuro.polymtl.ca/data/git-datasets.html#making-a-pull-request
