### ISSUE TITLE
Grant dataset access to Yehuda for the totalsegmentator-mri project

### ISSUE THREAD

**Issue by NathanMolinier** [neuropoly/data-management#320]
## Description

In the context of the total segmentator MRI project, we git-annexed several datasets to track the data used but Yehuda currently does not have access to some of these specific datasets:
- [x] goldatlas
- [x] mrspineseg-challenge-2021
- [x] lumbar-nusantara
- [x] synthrad-challenge-2023

Would it be possible to grant him access to these datasets ?

**Comment by mguaypaq** [comment]
@yw7 Done! Sorry for the wait.
