### ISSUE TITLE
Adding 7T MP2RAGE data from Leipzig

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#322]
Contact: Falk Eippert
suggestion for name: <s>`leipzig-7t-mprage`</s> `hc-leipzig-7t-mp2rage`

~~~
valosek@macbook-pro:~/Downloads/MP2RAGE_2share$ tree
.
├── sub-sspr17
│   ├── anat.nii.gz
│   └── anat_crop_biascorr_denoise.nii.gz
├── sub-sspr18
│   ├── anat.nii.gz
│   └── anat_crop_biascorr_denoise.nii.gz
├── sub-sspr19
│   ├── anat.nii.gz
│   └── anat_crop_biascorr_denoise.nii.gz
├── sub-sspr20
│   ├── anat.nii.gz
│   └── anat_crop_biascorr_denoise.nii.gz
├── sub-sspr21
│   ├── anat.nii.gz
│   └── anat_crop_biascorr_denoise.nii.gz
...
~~~

**Comment by valosekj** [comment]
Do we want to put `anat_crop_biascorr_denoise` images to the root directory or to derivatives?

`root`:

```console
.
├── dataset_description.json
├── participants.tsv
├── sub-sspr17
│   └── anat
│       ├── sub-sspr17_inv-2_MP2RAGE.nii.gz
│       └── sub-sspr17_desc-crop_biascorr_denoise_inv-2_MP2RAGE.nii.gz
├── sub-sspr18
│   └── anat
│       ├── sub-sspr18_inv-2_MP2RAGE.nii.gz
│       └── sub-sspr18_desc-crop_biascorr_denoise_inv-2_MP2RAGE.nii.gz
...
```

`derivatives`:

```console
.
├── dataset_description.json
├── participants.tsv
├── sub-sspr17
│   └── anat
│       └── sub-sspr17_inv-2_MP2RAGE.nii.gz
├── sub-sspr18
│   └── anat
│       └── sub-sspr18_inv-2_MP2RAGE.nii.gz
...
└── derivatives
    └── preprocessing
        ├── sub-sspr17
        │   └── anat
        │       └── sub-sspr17_desc-crop_biascorr_denoise_inv-2_MP2RAGE.nii.gz
        ├── sub-sspr18
        │   └── anat
        │       └── sub-sspr18_desc-crop_biascorr_denoise_inv-2_MP2RAGE.nii.gz
...
```

(I'm using `inv-2_MP2RAGE` based on https://github.com/ivadomed/model-spinal-rootlets/issues/45)
(Useful resource: [MP2RAGE bids-example](https://github.com/bids-standard/bids-examples/tree/eff47f104210a142a71abd058417fc91a82ba95a/qmri_mp2rage/sub-1/anat))

**Comment by jcohenadad** [comment]
> I'm using inv-2_MP2RAGE based on https://github.com/ivadomed/model-spinal-rootlets/issues/45

excellent

We should also ask for the first inversion, and the reconstructed UNI data. If we do get the UNI data, we should call this dataset mp2rage-- if not, let's keep mprage

**Comment by valosekj** [comment]
Meanwhile, @mguaypaq, could you please initialize a new dataset (<s>`leipzig-7t-mprage`</s> `leipzig-7t-mp2rage`) and add me as a collaborator? Thanks!

**Comment by mguaypaq** [comment]
@nullnik-0 do you want to do it? It would be a good occasion to test [the new admin instructions](https://github.com/neuropoly/intranet.neuro.polymtl.ca/pull/126). Feel free to ping me on slack if anything is unclear.

**Comment by valosekj** [comment]
> We should also ask for the first inversion, and the reconstructed UNI data. If we do get the UNI data, we should call this dataset mp2rage-- if not, let's keep mprage

👍🏻 

@NathanMolinier, just FYI, we now have the following three images for each subject:

```console
- sub-sspr17/sub-sspr17_acq-ND_inv-1_MP2RAGE.nii.gz
- sub-sspr17/sub-sspr17_acq-ND_inv-2_MP2RAGE.nii.gz
- sub-sspr17/sub-sspr17_acq-ND_UNI.nii.gz
```

**Comment by NathanMolinier** [comment]
> @NathanMolinier, just FYI, we now have the following three images for each subject:

Seems good to me !

Update: For records, we used `_UNIT1` instead of `_UNI` to be bids compliant

**Comment by NathanMolinier** [comment]
> We should also ask for the first inversion, and the reconstructed UNI data. If we do get the UNI data, we should call this dataset mp2rage

Should we rename this dataset `leipzig-7t-mp2rage` ? As mentioned by @jcohenadad

**Comment by valosekj** [comment]
> > We should also ask for the first inversion, and the reconstructed UNI data. If we do get the UNI data, we should call this dataset mp2rage
> 
> Should we rename this dataset `leipzig-7t-mp2rage` ? As mentioned by @jcohenadad

Yes! The images are MP2RAGE.

**Comment by NathanMolinier** [comment]
Regarding subject naming (`sub-sspr17`) do we want to use zero padding (`sub-sspr017`) is case we receive more data ? But even though, according to [bids](https://bids-specification.readthedocs.io/en/stable/common-principles.html#entities), it is not mandatory.

Update: maybe we can keep the names without padding and update if we receive more data

**Comment by NathanMolinier** [comment]
@nullnik-0 could you initialize the dataset `hc-leipzig-7t-mp2rage` and grant me writing access ? Thank you

**Comment by jcohenadad** [comment]
> Update: maybe we can keep the names without padding and update if we receive more data

yes-- i don't think we will receive more data (or at least no more than 100)

**Comment by nullnik-0** [comment]
> @nullnik-0 could you initialize the dataset hc-leipzig-7t-mp2rage and grant me writing access ?

Apologies for the delay. The dataset has been initialized and is accessible [here](https://data.neuro.polymtl.ca/datasets/hc-leipzig-7t-mp2rage/settings). @valosekj and @NathanMolinier should both have write access. Let me know if there are any issues.
