### ISSUE TITLE
New dataset `hc-ucsf-psir`

### ISSUE THREAD

**Issue by Nilser3** [neuropoly/data-management#323]
# Description

I would like to push a new dataset `ucsf-gm-psir` to git-annex server. 

Is a dataset shared by our UCSF collaborators, contains 110 subjects with:

`anat`: axial PSIR images from healthy controls (one slice by subject) at C2-3 level
`GT`: GM manual segmentation

Here the [qc_ucsf-gm-psir-gm.zip](https://github.com/user-attachments/files/15862358/qc_ucsf-gm-psir-gm.zip) checking GM segmentation

**Comment by Nilser3** [comment]
## Generating SC GTs

`sub-0047_acq-ax_PSIR`

1. Applying `seg_sc_contrast_agnostic` model [v2.4](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.4)

<br /><img src="https://github.com/neuropoly/data-management/assets/77469192/d249a8eb-d765-4c09-9492-435250f9e3f5" width="500px;" alt=""/>


2. Applying `sct_deepseg_sc` -c t1

<br /><img src="https://github.com/neuropoly/data-management/assets/77469192/41072df1-b44d-4ca7-9737-e7e2b79b416d" width="500px;" alt=""/>


QC here: [qc_ucsf-gm-psir.zip](https://github.com/user-attachments/files/15862243/qc_ucsf-gm-psir.zip) 


**Legend**
1. _contrast-agnostic.nii.gz -> contrast_agnostic model v2.4
2. _deepseg_sc.nii.gz -> sct_deepseg_sc -c t1

**Comment by Nilser3** [comment]
# Generating SC GTs

Because the [contrast-agnostic model v2.4](https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/releases/tag/v2.4) failed to segment the subject `sub-0047` (which is a single 2D slice, see segmentations above), 
I made a merge in Z of 40 slices, building a 3D volume where I applied the same contrast-agnostic model.

![PSIR_sc](https://github.com/neuropoly/data-management/assets/77469192/3386a7a5-2b4d-4825-96d1-6e309e57c6e0)

We have good results in the central slices (first column), but irregularities in the upper and lower ends:

- Upper last slice
![image](https://github.com/neuropoly/data-management/assets/77469192/9c7711ac-5305-428a-b2ee-c4a549e66438)

- Lower last slice
![image](https://github.com/neuropoly/data-management/assets/77469192/e1cfd922-3c3c-421a-8336-0204ca512409)

Maybe we should put an informative message about the use of `contrast-agnostic` model when applying it to 2D images? feedback pls @naga-karthik

**Comment by naga-karthik** [comment]
Hey Nilser, thanks for the detailed segmentation images! it's surprising that the contrast-agnostic model is not working that well -- i'm guessing that's mainly because these are single-slice images? the v2.4 model was trained will all 3D images AND didn't have axial PSIR images (only sagittal PSIR scans were available)

> I made a merge in Z of 40 slices,

what do you mean by this? where is this `40` coming from? I have a few more questions:
1. what is the size of the original input image (i.e. matrix dimensions)? 
2. what is the size after merging the z-slices? 


>  but irregularities in the upper and lower ends:

yeah, this is an issue because of padding the images to a common size during training. Because you're are merging slices anyway to make it a 3D input, maybe you can also discard the top and bottom slices? i.e. your actual SC slice would be in the middle -- which I see has a good segmentation already. let me know what you think!

**Comment by Nilser3** [comment]
Thanks you @naga-karthik 

Here in detail:
I made a merge on the Z-axis of 40 2D slices (repeat the same slice).

Original input image `2D slice`:
- shape: 256x256x1 , resolution: 0.7812x0.7812x5

`3D vol`: 
- shape: 256x256x40, resolution: 0.7812x0.7812x5

Yes, I think the model makes a good segmentation in the middle of a 3D volume, maybe this would be the approach when the model confronts 2D images in input.

**Comment by jcohenadad** [comment]
> I made a merge in Z of 40 slices, building a 3D volume where I applied the same contrast-agnostic model.

what if we pad using mirroring data to avoid edge cases? I think we already talked about it @naga-karthik @Nilser3 -- we should add this as preprocessing of sct_deepseg before inference

**Comment by naga-karthik** [comment]
Yeah, this could be done -- I opened an issue on SCT regarding this

**Comment by Nilser3** [comment]
Hi @mguaypaq ,
Could you please create a repo for the dataset: `hc-ucsf-psir`

Thanks you

**Comment by naga-karthik** [comment]
Maybe it shoudl be `gm-psir-ucsf` ? a lot of our datasets have center names at the end (e.g. `sci-zurich`, `dcm-paris`, `lumbar-epfl` etc. )

**Comment by jcohenadad** [comment]
~how about simply `psir-ucsf`? i'm afraid 'gm' will be confusing. We do have a 'gmseg' but it was specifically for a challenge~

actually, according to [our convention](https://github.com/ivadomed/ivadomed/wiki/repositories#data), the contrast goes at the end. So it should be `ucsf-psir` then

**EDIT 20240620_124453**: I just edited our convention, to add `hc-` in the beginning, so it would be `hc-ucsf-psir` if that's ok with everyone

**Comment by Nilser3** [comment]
Hi @mguaypaq , could you create a repo for  `hc-ucsf-psir` dataset please.
Thanks you

**Comment by mguaypaq** [comment]
I created the repository and gave write access to @Nilser3:
https://data.neuro.polymtl.ca/datasets/hc-ucsf-psir

**Comment by Nilser3** [comment]
Thanks you @mguaypaq 
PR done!

**Comment by Nilser3** [comment]
PR was reviewed and merged !
