### ISSUE TITLE
`philadelphia-pediatric` - different conventions for disc labels

### ISSUE THREAD

**Issue by valosekj** [neuropoly/data-management#328]
When working on the `philadelphia-pediatric` dataset in the context of https://github.com/ivadomed/model-spinal-rootlets/issues/19, @KaterinaKrejci231054 noticed that `derivatives/labels` contains disc labels with two different conventions.

## Convention 1

Disc labels are located in the middle of the cord. For example, `sub-101/anat/sub-101_rec-composed_T2w_labels-disc.nii.gz`:

<details><summary>image</summary>

![sub-101](https://github.com/neuropoly/data-management/assets/39456460/dec16e7b-a411-44f4-b277-67a7d017663c)

</details>

Notice that the labels are located in the middle of the cord at the level of discs, i.e., not in the middle of each vertebral level as specified by our ["Vertebral levels" convention](https://spinalcordtoolbox.com/user_section/tutorials/vertebral-labeling/labeling-conventions.html).

## Convention 2

Disc labels are located on the posterior tip of each disc. For example, `sub-102/anat/sub-102_rec-composed_T2w_labels-disc.nii.gz`:

<details><summary>image</summary>

![sub-102](https://github.com/neuropoly/data-management/assets/39456460/7e63471a-2fec-43e0-94ab-e3f9b50d7589)

</details>

---

When looking at the JSON sidecars, it seems that labels for different conventions were created by different authors:

```console
valosek@macbook-pro:~/data/data.neuro.polymtl.ca/philadelphia-pediatric/derivatives/labels$ cat sub-101/anat/sub-101_rec-composed_T2w_labels-disc.json
{
    "Author": "Nadia Blostein",
    "Date": "2023-02-14 21:23:00",
    "Notes": "Corrected disc label 20, added disc label 21 (on SC, not on posterior disc)"
}
valosek@macbook-pro:~/data/data.neuro.polymtl.ca/philadelphia-pediatric/derivatives/labels$ cat sub-102/anat/sub-102_rec-composed_T2w_labels-disc.json
{
    "Author": "Sandrine Bedard",
    "Date": "2023-02-13 12:17:33"
}
```

---

Different disc positions (middle of the cord vs posterior tip of each disc) might have an impact on vert labeling (`sct_label_vertebrae -discfile`), registrations, or other processing steps. 
Should we unify the disc labels?

**Comment by jcohenadad** [comment]
> Should we unify the disc labels?

yes, definitely. Tagging @NathanMolinier

**Comment by NathanMolinier** [comment]
Yes, this is the goal indeed to only follow our [convention](https://spinalcordtoolbox.com/user_section/tutorials/vertebral-labeling/labeling-conventions.html), however so far, the main method we have been using `sct_label_vertebrae` is outputting discs positions in the middle of the cord. This is the reason we have this distinction

**Comment by valosekj** [comment]
Thank you for the feedback!

> > Should we unify the disc labels?
> 
> yes, definitely. 

Okay! We're gonna redo the discs to place them **_on the posterior tip of each disc_**.

**Comment by NathanMolinier** [comment]
If you want the discs labels to be projected onto the centerline, you can use the function `sct_label_utils` with the flag `-project-centerline`.

<img width="550" alt="Screenshot 2024-06-25 at 13 01 20" src="https://github.com/neuropoly/data-management/assets/68945192/6674cc44-34f6-4704-9b8f-845ed5fc09a9">

**Comment by valosekj** [comment]
Discs fixed (relabeled to be located on the posterior tip of each disc) in https://data.neuro.polymtl.ca/datasets/philadelphia-pediatric/pulls/1.
