### ISSUE TITLE
Creating new git-annex datasets repos

### ISSUE THREAD

**Issue by plbenveniste** [neuropoly/data-management#329]
Hi ! 

I found the tutorial to create git-annex repos ([here](https://github.com/neuropoly/intranet.neuro.polymtl.ca/blob/a59aca8ceadc57713ff41d99ff7aaa8d79a4b5a3/data/admin-guide.md)) which seems to be pretty straight-forward. In order to save time, I am wondering if I am allowed to create myself a git-annex repo? Or should this be done by @mguaypaq or @nullnik-0 ? 

Thanks in advance for your feedback.

**Comment by mguaypaq** [comment]
Sorry, maybe we'll make this self-service later on, but for now only [members of the admin team](https://data.neuro.polymtl.ca/org/datasets/teams/owners) can create repositories inside the `datasets/` org. (You can create private repositories under your username, but that's not our typical way of working.)

I'll create the repository.

**Comment by mguaypaq** [comment]
Done:
* https://github.com/ivadomed/ms-lesion-agnostic/issues/19#issuecomment-2223505014
* https://github.com/ivadomed/ms-lesion-agnostic/issues/20#issuecomment-2223508075
