### ISSUE TITLE
New dataset `infant-brain-basel`

### ISSUE THREAD

**Issue by amahlig** [neuropoly/data-management#331]
I would like to push a new dataset `infant-brain-basel` to our git-annex server. 
This is a public dataset (https://zenodo.org/records/6556135) and contains T1w and T2w images of 833 subjects from 0 to 36 months.

@mguaypaq, can you initialize the dataset and give me r/w permissions? Thank you!

**Comment by mguaypaq** [comment]
That's a good name, considering [our new naming convention](https://intranet.neuro.polymtl.ca/data/dataset-curation.html#naming-the-dataset). I'm amused that we're using "infant" as a species but it really makes sense.

I created the repository, and gave @amahlig write access:
https://data.neuro.polymtl.ca/datasets/infant-brain-basel

See [this intranet page](https://intranet.neuro.polymtl.ca/data/git-datasets.html#making-a-pull-request) for some step by step instructions on how to add your data to the repository. Roughly, the steps are:
1. Make a clone of the repository (which currently contains only some example files).
2. Put your dataset in there (feel free to modify/remove any of the example files) using normal tools (file explorer, shell commands, whatever).
3. Push your changes to the server.
