### ISSUE TITLE
add TOC in https://github.com/neuropoly/data-management/blob/master/internal-server.md

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#49]
for more convenient day-to-day usage

**Comment by kousu** [comment]
Ah I can do this now. I found https://github.com/ekalinin/github-markdown-toc. It's not quite perfect but it works pretty well.

**Comment by kousu** [comment]
https://github.com/neuropoly/data-management/pull/35/commits/d799cb3b3d8273d89e9e22cd5657e6e09031b762
