### ISSUE TITLE
sub-karoXXXX and sub-karoTobiasMSXXX --> are they the same?

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/data-management#61]
### Context

We would like to train a DL model to segment lesions on the Karolinska data.

We know the data will be longitudinal, so I asked @alexfoias to put the data under a `ses-01` subfolder. See issue [here](https://github.com/ivadomed/pipeline-ms-lesion/issues/4).

### Problem

While reviewing this PR https://github.com/neuropoly/data-management/issues/60, I realized that Anne sent us segmentations from _another_ dataset: sub-karoXXXX.

So my questions are:
- do sub-karoXXXX and sub-karoTobiasMSXXX overlap? (ie: duplicated data)?
- if not, are we _sure_ Anne segmented the right dataset? (ie: is sub-karoXXXX the one that is going to be longitudinal?)
- if Anne segmented the right dataset, and @alexfoias should create the "ses-01" folder for this dataset instead.

@alexfoias @charleygros do you have any insights?

**Comment by charleygros** [comment]
> @charleygros do you have any insights?

I don't know about this, don't know what data has been sent to Anne etc.
But I'm happy to have a look, ie comparing XXXX and XXX. brb

**Comment by jcohenadad** [comment]
I checked and no, they are not the same. These are the data under karo:
~~~
drwx------  1 julien  staff  2472  1 Aug  2016 20160801_tobias
drwx------  1 julien  staff  2846 12 Mar  2017 2017-tobias
drwx------  1 julien  staff  1928 13 Aug  2019 2017-tobias-MS
drwx------  1 julien  staff   264  9 Jan  2019 20181228_tobias
drwx------  1 julien  staff   264  2 Dec  2019 20191203_repro_symri
drwx------  1 julien  staff  4070  9 Dec  2019 20191204_z_score_project
drwx------  1 julien  staff   264 15 Jun  2020 20200612_longitudinal
~~~

karoXXXX corresponds to the 20200612_longitudinal folder. We can close
