### ISSUE TITLE
Accidental data erase on duke

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/data-management#94]
@kousu Accidentaly erased some files from duke when trying to cleanup his grames home folder on a server.

Checked the log on  [duke/logs/Backup-15-06-2021_01-00-36.log](https://pastebin.com/1Wst72AN) and the missing files are listed there.

@jsdecarie Recovered the data from sct_testing from backup.

@alexfoias Investigated the differences between the backup restore (`duke/sct_testing`) and the one after the erase (`duke/sct_testing_old`).

Here is the list: https://pastebin.com/zJcEDzaU

Showterm here: https://showterm.io/f4c6b380614dbf9c03ad2

**Comment by alexfoias** [comment]
The restore seemed to recovered the missing files. @kousu @jcohenadad I think we can go ahead and drop the `duke/sct_testing_old`.

**Comment by kousu** [comment]
Related: https://github.com/neuropoly/computers/issues/124
